<?php


/**
 * This class defines the structure of the 'tbalunomatricula' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Mar 16 17:38:45 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TbalunomatriculaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TbalunomatriculaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tbalunomatricula');
		$this->setPhpName('Tbalunomatricula');
		$this->setClassname('Tbalunomatricula');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('tbpessoa_id_pessoa_seq');
		// columns
		$this->addColumn('ID_PESSOA', 'IdPessoa', 'INTEGER', true, null, null);
		$this->addPrimaryKey('MATRICULA', 'Matricula', 'BIGINT', true, null, null);
		$this->addColumn('NOME', 'Nome', 'VARCHAR', true, 100, null);
		$this->addColumn('CELULAR', 'Celular', 'VARCHAR', false, 15, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 100, null);
		$this->addColumn('FONE_RESIDENCIAL', 'FoneResidencial', 'VARCHAR', false, 15, null);
		$this->addForeignKey('ID_NECES_ESPECIAL', 'IdNecesEspecial', 'VARCHAR', 'tbnecesespecial', 'ID_NECES_ESPECIAL', true, 255, null);
		$this->addColumn('DT_NASCIMENTO', 'DtNascimento', 'DATE', true, null, null);
		$this->addForeignKey('NATURALIDADE', 'Naturalidade', 'INTEGER', 'tbcidade', 'ID_CIDADE', true, null, null);
		$this->addColumn('UF_NASCIMENTO', 'UfNascimento', 'CHAR', false, 2, null);
		$this->addForeignKey('NACIONALIDADE', 'Nacionalidade', 'INTEGER', 'tbpais', 'ID_PAIS', true, null, null);
		$this->addColumn('SEXO', 'Sexo', 'CHAR', true, 1, null);
		$this->addColumn('ESTADO_CIVIL', 'EstadoCivil', 'VARCHAR', false, 15, null);
		$this->addColumn('TITULO', 'Titulo', 'VARCHAR', false, 20, null);
		$this->addColumn('TITULO_ZONA', 'TituloZona', 'INTEGER', false, null, null);
		$this->addColumn('TITULO_SECAO', 'TituloSecao', 'INTEGER', false, null, null);
		$this->addColumn('RG', 'Rg', 'VARCHAR', true, 20, null);
		$this->addColumn('RG_DT_EXPED', 'RgDtExped', 'DATE', false, null, null);
		$this->addColumn('RG_ORG_EXPED', 'RgOrgExped', 'VARCHAR', false, 10, null);
		$this->addColumn('CPF', 'Cpf', 'VARCHAR', true, 11, null);
		$this->addColumn('RESERVISTA', 'Reservista', 'VARCHAR', false, 20, null);
		$this->addColumn('PAI', 'Pai', 'VARCHAR', false, 50, null);
		$this->addColumn('MAE', 'Mae', 'VARCHAR', false, 50, null);
		$this->addForeignKey('CEP', 'Cep', 'VARCHAR', 'tblogradouro', 'CEP', true, 9, null);
		$this->addColumn('NUMERO', 'Numero', 'VARCHAR', true, 8, null);
		$this->addColumn('COMPLEMENTO', 'Complemento', 'VARCHAR', false, 50, null);
		$this->addForeignKey('ID_VERSAO_CURSO', 'IdVersaoCurso', 'INTEGER', 'tbcursoversao', 'ID_VERSAO_CURSO', true, null, null);
		$this->addForeignKey('ID_TIPO_INGRESSO', 'IdTipoIngresso', 'INTEGER', 'tbtipoingresso', 'ID_TIPO_INGRESSO', true, null, null);
		$this->addColumn('DT_INGRESSO', 'DtIngresso', 'DATE', true, null, null);
		$this->addForeignKey('ID_SITUACAO', 'IdSituacao', 'INTEGER', 'tbalunosituacao', 'ID_SITUACAO', true, null, null);
		$this->addColumn('DT_SITUACAO', 'DtSituacao', 'DATE', false, null, null);
		$this->addForeignKey('ID_2GRAU', 'Id2grau', 'INTEGER', 'tbinstexterna', 'ID_INST_EXTERNA', false, null, null);
		$this->addColumn('ANO_CONCL_2GRAU', 'AnoConcl2grau', 'INTEGER', false, null, null);
		$this->addColumn('OP_INGRESSO', 'OpIngresso', 'INTEGER', false, null, 0);
		$this->addForeignKey('ID_POLO', 'IdPolo', 'INTEGER', 'tbpolos', 'ID_POLO', true, null, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'DATE', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'DATE', false, null, null);
		$this->addColumn('CREATED_BY', 'CreatedBy', 'VARCHAR', false, 20, null);
		$this->addColumn('UPDATED_BY', 'UpdatedBy', 'VARCHAR', false, 20, null);
		$this->addForeignKey('ID_RACA', 'IdRaca', 'INTEGER', 'tbaluno_racacor', 'ID_RACA', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Tbnecesespecial', 'Tbnecesespecial', RelationMap::MANY_TO_ONE, array('id_neces_especial' => 'id_neces_especial', ), null, null);
    $this->addRelation('Tbcidade', 'Tbcidade', RelationMap::MANY_TO_ONE, array('naturalidade' => 'id_cidade', ), null, null);
    $this->addRelation('Tbpais', 'Tbpais', RelationMap::MANY_TO_ONE, array('nacionalidade' => 'id_pais', ), null, null);
    $this->addRelation('Tblogradouro', 'Tblogradouro', RelationMap::MANY_TO_ONE, array('cep' => 'cep', ), null, null);
    $this->addRelation('Tbcursoversao', 'Tbcursoversao', RelationMap::MANY_TO_ONE, array('id_versao_curso' => 'id_versao_curso', ), null, null);
    $this->addRelation('Tbtipoingresso', 'Tbtipoingresso', RelationMap::MANY_TO_ONE, array('id_tipo_ingresso' => 'id_tipo_ingresso', ), null, null);
    $this->addRelation('Tbalunosituacao', 'Tbalunosituacao', RelationMap::MANY_TO_ONE, array('id_situacao' => 'id_situacao', ), null, null);
    $this->addRelation('Tbinstexterna', 'Tbinstexterna', RelationMap::MANY_TO_ONE, array('id_2grau' => 'id_inst_externa', ), null, null);
    $this->addRelation('Tbpolos', 'Tbpolos', RelationMap::MANY_TO_ONE, array('id_polo' => 'id_polo', ), null, null);
    $this->addRelation('Tbalunoracacor', 'Tbalunoracacor', RelationMap::MANY_TO_ONE, array('id_raca' => 'id_raca', ), null, null);
    $this->addRelation('TbmatriculaComprovante', 'TbmatriculaComprovante', RelationMap::ONE_TO_MANY, array('matricula' => 'matricula', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // TbalunomatriculaTableMap
