<?php


/**
 * This class defines the structure of the 'tbturma_sumula' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Mar 16 17:38:56 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TbturmaSumulaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TbturmaSumulaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('tbturma_sumula');
		$this->setPhpName('TbturmaSumula');
		$this->setClassname('TbturmaSumula');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('tbturma_sumula_id_sumula_seq');
		// columns
		$this->addPrimaryKey('ID_SUMULA', 'IdSumula', 'INTEGER', true, null, null);
		$this->addForeignKey('ID_TURMA', 'IdTurma', 'INTEGER', 'tbturma', 'ID_TURMA', true, null, null);
		$this->addColumn('DATA', 'Data', 'DATE', true, null, null);
		$this->addColumn('DESCRICAO', 'Descricao', 'LONGVARCHAR', true, null, null);
		$this->addColumn('MATRICULA_PROF', 'MatriculaProf', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Tbturma', 'Tbturma', RelationMap::MANY_TO_ONE, array('id_turma' => 'id_turma', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TbturmaSumulaTableMap
