<?php


/**
 * Base class that represents a query for the 'tbloadaluno' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Apr 23 17:54:37 2013
 *
 * @method TbloadalunoQuery orderByMatricula($order = Criteria::ASC) Order by the matricula column
 * @method TbloadalunoQuery orderByNome($order = Criteria::ASC) Order by the nome column
 * @method TbloadalunoQuery orderBySexo($order = Criteria::ASC) Order by the sexo column
 * @method TbloadalunoQuery orderByRg($order = Criteria::ASC) Order by the rg column
 * @method TbloadalunoQuery orderByRgOrgExped($order = Criteria::ASC) Order by the rg_org_exped column
 * @method TbloadalunoQuery orderByCpf($order = Criteria::ASC) Order by the cpf column
 * @method TbloadalunoQuery orderByIdVersaoCurso($order = Criteria::ASC) Order by the id_versao_curso column
 * @method TbloadalunoQuery orderByIdTipoIngresso($order = Criteria::ASC) Order by the id_tipo_ingresso column
 * @method TbloadalunoQuery orderByIdSituacao($order = Criteria::ASC) Order by the id_situacao column
 * @method TbloadalunoQuery orderByClassificacao($order = Criteria::ASC) Order by the classificacao column
 * @method TbloadalunoQuery orderByOpcao($order = Criteria::ASC) Order by the opcao column
 * @method TbloadalunoQuery orderByProcesso($order = Criteria::ASC) Order by the processo column
 * @method TbloadalunoQuery orderByOpIngresso($order = Criteria::ASC) Order by the op_ingresso column
 * @method TbloadalunoQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method TbloadalunoQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method TbloadalunoQuery orderByCreatedBy($order = Criteria::ASC) Order by the created_by column
 * @method TbloadalunoQuery orderByUpdatedBy($order = Criteria::ASC) Order by the updated_by column
 *
 * @method TbloadalunoQuery groupByMatricula() Group by the matricula column
 * @method TbloadalunoQuery groupByNome() Group by the nome column
 * @method TbloadalunoQuery groupBySexo() Group by the sexo column
 * @method TbloadalunoQuery groupByRg() Group by the rg column
 * @method TbloadalunoQuery groupByRgOrgExped() Group by the rg_org_exped column
 * @method TbloadalunoQuery groupByCpf() Group by the cpf column
 * @method TbloadalunoQuery groupByIdVersaoCurso() Group by the id_versao_curso column
 * @method TbloadalunoQuery groupByIdTipoIngresso() Group by the id_tipo_ingresso column
 * @method TbloadalunoQuery groupByIdSituacao() Group by the id_situacao column
 * @method TbloadalunoQuery groupByClassificacao() Group by the classificacao column
 * @method TbloadalunoQuery groupByOpcao() Group by the opcao column
 * @method TbloadalunoQuery groupByProcesso() Group by the processo column
 * @method TbloadalunoQuery groupByOpIngresso() Group by the op_ingresso column
 * @method TbloadalunoQuery groupByCreatedAt() Group by the created_at column
 * @method TbloadalunoQuery groupByUpdatedAt() Group by the updated_at column
 * @method TbloadalunoQuery groupByCreatedBy() Group by the created_by column
 * @method TbloadalunoQuery groupByUpdatedBy() Group by the updated_by column
 *
 * @method TbloadalunoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method TbloadalunoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method TbloadalunoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method TbloadalunoQuery leftJoinTbcursoversao($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tbcursoversao relation
 * @method TbloadalunoQuery rightJoinTbcursoversao($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tbcursoversao relation
 * @method TbloadalunoQuery innerJoinTbcursoversao($relationAlias = null) Adds a INNER JOIN clause to the query using the Tbcursoversao relation
 *
 * @method TbloadalunoQuery leftJoinTbtipoingresso($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tbtipoingresso relation
 * @method TbloadalunoQuery rightJoinTbtipoingresso($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tbtipoingresso relation
 * @method TbloadalunoQuery innerJoinTbtipoingresso($relationAlias = null) Adds a INNER JOIN clause to the query using the Tbtipoingresso relation
 *
 * @method TbloadalunoQuery leftJoinTbalunosituacao($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tbalunosituacao relation
 * @method TbloadalunoQuery rightJoinTbalunosituacao($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tbalunosituacao relation
 * @method TbloadalunoQuery innerJoinTbalunosituacao($relationAlias = null) Adds a INNER JOIN clause to the query using the Tbalunosituacao relation
 *
 * @method Tbloadaluno findOne(PropelPDO $con = null) Return the first Tbloadaluno matching the query
 * @method Tbloadaluno findOneOrCreate(PropelPDO $con = null) Return the first Tbloadaluno matching the query, or a new Tbloadaluno object populated from the query conditions when no match is found
 *
 * @method Tbloadaluno findOneByMatricula(string $matricula) Return the first Tbloadaluno filtered by the matricula column
 * @method Tbloadaluno findOneByNome(string $nome) Return the first Tbloadaluno filtered by the nome column
 * @method Tbloadaluno findOneBySexo(string $sexo) Return the first Tbloadaluno filtered by the sexo column
 * @method Tbloadaluno findOneByRg(string $rg) Return the first Tbloadaluno filtered by the rg column
 * @method Tbloadaluno findOneByRgOrgExped(string $rg_org_exped) Return the first Tbloadaluno filtered by the rg_org_exped column
 * @method Tbloadaluno findOneByCpf(string $cpf) Return the first Tbloadaluno filtered by the cpf column
 * @method Tbloadaluno findOneByIdVersaoCurso(int $id_versao_curso) Return the first Tbloadaluno filtered by the id_versao_curso column
 * @method Tbloadaluno findOneByIdTipoIngresso(int $id_tipo_ingresso) Return the first Tbloadaluno filtered by the id_tipo_ingresso column
 * @method Tbloadaluno findOneByIdSituacao(int $id_situacao) Return the first Tbloadaluno filtered by the id_situacao column
 * @method Tbloadaluno findOneByClassificacao(int $classificacao) Return the first Tbloadaluno filtered by the classificacao column
 * @method Tbloadaluno findOneByOpcao(string $opcao) Return the first Tbloadaluno filtered by the opcao column
 * @method Tbloadaluno findOneByProcesso(string $processo) Return the first Tbloadaluno filtered by the processo column
 * @method Tbloadaluno findOneByOpIngresso(int $op_ingresso) Return the first Tbloadaluno filtered by the op_ingresso column
 * @method Tbloadaluno findOneByCreatedAt(string $created_at) Return the first Tbloadaluno filtered by the created_at column
 * @method Tbloadaluno findOneByUpdatedAt(string $updated_at) Return the first Tbloadaluno filtered by the updated_at column
 * @method Tbloadaluno findOneByCreatedBy(string $created_by) Return the first Tbloadaluno filtered by the created_by column
 * @method Tbloadaluno findOneByUpdatedBy(string $updated_by) Return the first Tbloadaluno filtered by the updated_by column
 *
 * @method array findByMatricula(string $matricula) Return Tbloadaluno objects filtered by the matricula column
 * @method array findByNome(string $nome) Return Tbloadaluno objects filtered by the nome column
 * @method array findBySexo(string $sexo) Return Tbloadaluno objects filtered by the sexo column
 * @method array findByRg(string $rg) Return Tbloadaluno objects filtered by the rg column
 * @method array findByRgOrgExped(string $rg_org_exped) Return Tbloadaluno objects filtered by the rg_org_exped column
 * @method array findByCpf(string $cpf) Return Tbloadaluno objects filtered by the cpf column
 * @method array findByIdVersaoCurso(int $id_versao_curso) Return Tbloadaluno objects filtered by the id_versao_curso column
 * @method array findByIdTipoIngresso(int $id_tipo_ingresso) Return Tbloadaluno objects filtered by the id_tipo_ingresso column
 * @method array findByIdSituacao(int $id_situacao) Return Tbloadaluno objects filtered by the id_situacao column
 * @method array findByClassificacao(int $classificacao) Return Tbloadaluno objects filtered by the classificacao column
 * @method array findByOpcao(string $opcao) Return Tbloadaluno objects filtered by the opcao column
 * @method array findByProcesso(string $processo) Return Tbloadaluno objects filtered by the processo column
 * @method array findByOpIngresso(int $op_ingresso) Return Tbloadaluno objects filtered by the op_ingresso column
 * @method array findByCreatedAt(string $created_at) Return Tbloadaluno objects filtered by the created_at column
 * @method array findByUpdatedAt(string $updated_at) Return Tbloadaluno objects filtered by the updated_at column
 * @method array findByCreatedBy(string $created_by) Return Tbloadaluno objects filtered by the created_by column
 * @method array findByUpdatedBy(string $updated_by) Return Tbloadaluno objects filtered by the updated_by column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTbloadalunoQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseTbloadalunoQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Tbloadaluno', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new TbloadalunoQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     TbloadalunoQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return TbloadalunoQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof TbloadalunoQuery) {
            return $criteria;
        }
        $query = new TbloadalunoQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Tbloadaluno|Tbloadaluno[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = TbloadalunoPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(TbloadalunoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Tbloadaluno A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT MATRICULA, NOME, SEXO, RG, RG_ORG_EXPED, CPF, ID_VERSAO_CURSO, ID_TIPO_INGRESSO, ID_SITUACAO, CLASSIFICACAO, OPCAO, PROCESSO, OP_INGRESSO, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY FROM tbloadaluno WHERE MATRICULA = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Tbloadaluno();
            $obj->hydrate($row);
            TbloadalunoPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Tbloadaluno|Tbloadaluno[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Tbloadaluno[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(TbloadalunoPeer::MATRICULA, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(TbloadalunoPeer::MATRICULA, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the matricula column
     *
     * Example usage:
     * <code>
     * $query->filterByMatricula(1234); // WHERE matricula = 1234
     * $query->filterByMatricula(array(12, 34)); // WHERE matricula IN (12, 34)
     * $query->filterByMatricula(array('min' => 12)); // WHERE matricula > 12
     * </code>
     *
     * @param     mixed $matricula The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByMatricula($matricula = null, $comparison = null)
    {
        if (is_array($matricula) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(TbloadalunoPeer::MATRICULA, $matricula, $comparison);
    }

    /**
     * Filter the query on the nome column
     *
     * Example usage:
     * <code>
     * $query->filterByNome('fooValue');   // WHERE nome = 'fooValue'
     * $query->filterByNome('%fooValue%'); // WHERE nome LIKE '%fooValue%'
     * </code>
     *
     * @param     string $nome The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByNome($nome = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($nome)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $nome)) {
                $nome = str_replace('*', '%', $nome);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::NOME, $nome, $comparison);
    }

    /**
     * Filter the query on the sexo column
     *
     * Example usage:
     * <code>
     * $query->filterBySexo('fooValue');   // WHERE sexo = 'fooValue'
     * $query->filterBySexo('%fooValue%'); // WHERE sexo LIKE '%fooValue%'
     * </code>
     *
     * @param     string $sexo The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterBySexo($sexo = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($sexo)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $sexo)) {
                $sexo = str_replace('*', '%', $sexo);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::SEXO, $sexo, $comparison);
    }

    /**
     * Filter the query on the rg column
     *
     * Example usage:
     * <code>
     * $query->filterByRg('fooValue');   // WHERE rg = 'fooValue'
     * $query->filterByRg('%fooValue%'); // WHERE rg LIKE '%fooValue%'
     * </code>
     *
     * @param     string $rg The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByRg($rg = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($rg)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $rg)) {
                $rg = str_replace('*', '%', $rg);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::RG, $rg, $comparison);
    }

    /**
     * Filter the query on the rg_org_exped column
     *
     * Example usage:
     * <code>
     * $query->filterByRgOrgExped('fooValue');   // WHERE rg_org_exped = 'fooValue'
     * $query->filterByRgOrgExped('%fooValue%'); // WHERE rg_org_exped LIKE '%fooValue%'
     * </code>
     *
     * @param     string $rgOrgExped The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByRgOrgExped($rgOrgExped = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($rgOrgExped)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $rgOrgExped)) {
                $rgOrgExped = str_replace('*', '%', $rgOrgExped);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::RG_ORG_EXPED, $rgOrgExped, $comparison);
    }

    /**
     * Filter the query on the cpf column
     *
     * Example usage:
     * <code>
     * $query->filterByCpf('fooValue');   // WHERE cpf = 'fooValue'
     * $query->filterByCpf('%fooValue%'); // WHERE cpf LIKE '%fooValue%'
     * </code>
     *
     * @param     string $cpf The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByCpf($cpf = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($cpf)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $cpf)) {
                $cpf = str_replace('*', '%', $cpf);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::CPF, $cpf, $comparison);
    }

    /**
     * Filter the query on the id_versao_curso column
     *
     * Example usage:
     * <code>
     * $query->filterByIdVersaoCurso(1234); // WHERE id_versao_curso = 1234
     * $query->filterByIdVersaoCurso(array(12, 34)); // WHERE id_versao_curso IN (12, 34)
     * $query->filterByIdVersaoCurso(array('min' => 12)); // WHERE id_versao_curso > 12
     * </code>
     *
     * @see       filterByTbcursoversao()
     *
     * @param     mixed $idVersaoCurso The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByIdVersaoCurso($idVersaoCurso = null, $comparison = null)
    {
        if (is_array($idVersaoCurso)) {
            $useMinMax = false;
            if (isset($idVersaoCurso['min'])) {
                $this->addUsingAlias(TbloadalunoPeer::ID_VERSAO_CURSO, $idVersaoCurso['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($idVersaoCurso['max'])) {
                $this->addUsingAlias(TbloadalunoPeer::ID_VERSAO_CURSO, $idVersaoCurso['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::ID_VERSAO_CURSO, $idVersaoCurso, $comparison);
    }

    /**
     * Filter the query on the id_tipo_ingresso column
     *
     * Example usage:
     * <code>
     * $query->filterByIdTipoIngresso(1234); // WHERE id_tipo_ingresso = 1234
     * $query->filterByIdTipoIngresso(array(12, 34)); // WHERE id_tipo_ingresso IN (12, 34)
     * $query->filterByIdTipoIngresso(array('min' => 12)); // WHERE id_tipo_ingresso > 12
     * </code>
     *
     * @see       filterByTbtipoingresso()
     *
     * @param     mixed $idTipoIngresso The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByIdTipoIngresso($idTipoIngresso = null, $comparison = null)
    {
        if (is_array($idTipoIngresso)) {
            $useMinMax = false;
            if (isset($idTipoIngresso['min'])) {
                $this->addUsingAlias(TbloadalunoPeer::ID_TIPO_INGRESSO, $idTipoIngresso['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($idTipoIngresso['max'])) {
                $this->addUsingAlias(TbloadalunoPeer::ID_TIPO_INGRESSO, $idTipoIngresso['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::ID_TIPO_INGRESSO, $idTipoIngresso, $comparison);
    }

    /**
     * Filter the query on the id_situacao column
     *
     * Example usage:
     * <code>
     * $query->filterByIdSituacao(1234); // WHERE id_situacao = 1234
     * $query->filterByIdSituacao(array(12, 34)); // WHERE id_situacao IN (12, 34)
     * $query->filterByIdSituacao(array('min' => 12)); // WHERE id_situacao > 12
     * </code>
     *
     * @see       filterByTbalunosituacao()
     *
     * @param     mixed $idSituacao The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByIdSituacao($idSituacao = null, $comparison = null)
    {
        if (is_array($idSituacao)) {
            $useMinMax = false;
            if (isset($idSituacao['min'])) {
                $this->addUsingAlias(TbloadalunoPeer::ID_SITUACAO, $idSituacao['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($idSituacao['max'])) {
                $this->addUsingAlias(TbloadalunoPeer::ID_SITUACAO, $idSituacao['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::ID_SITUACAO, $idSituacao, $comparison);
    }

    /**
     * Filter the query on the classificacao column
     *
     * Example usage:
     * <code>
     * $query->filterByClassificacao(1234); // WHERE classificacao = 1234
     * $query->filterByClassificacao(array(12, 34)); // WHERE classificacao IN (12, 34)
     * $query->filterByClassificacao(array('min' => 12)); // WHERE classificacao > 12
     * </code>
     *
     * @param     mixed $classificacao The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByClassificacao($classificacao = null, $comparison = null)
    {
        if (is_array($classificacao)) {
            $useMinMax = false;
            if (isset($classificacao['min'])) {
                $this->addUsingAlias(TbloadalunoPeer::CLASSIFICACAO, $classificacao['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($classificacao['max'])) {
                $this->addUsingAlias(TbloadalunoPeer::CLASSIFICACAO, $classificacao['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::CLASSIFICACAO, $classificacao, $comparison);
    }

    /**
     * Filter the query on the opcao column
     *
     * Example usage:
     * <code>
     * $query->filterByOpcao('fooValue');   // WHERE opcao = 'fooValue'
     * $query->filterByOpcao('%fooValue%'); // WHERE opcao LIKE '%fooValue%'
     * </code>
     *
     * @param     string $opcao The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByOpcao($opcao = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($opcao)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $opcao)) {
                $opcao = str_replace('*', '%', $opcao);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::OPCAO, $opcao, $comparison);
    }

    /**
     * Filter the query on the processo column
     *
     * Example usage:
     * <code>
     * $query->filterByProcesso('fooValue');   // WHERE processo = 'fooValue'
     * $query->filterByProcesso('%fooValue%'); // WHERE processo LIKE '%fooValue%'
     * </code>
     *
     * @param     string $processo The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByProcesso($processo = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($processo)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $processo)) {
                $processo = str_replace('*', '%', $processo);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::PROCESSO, $processo, $comparison);
    }

    /**
     * Filter the query on the op_ingresso column
     *
     * Example usage:
     * <code>
     * $query->filterByOpIngresso(1234); // WHERE op_ingresso = 1234
     * $query->filterByOpIngresso(array(12, 34)); // WHERE op_ingresso IN (12, 34)
     * $query->filterByOpIngresso(array('min' => 12)); // WHERE op_ingresso > 12
     * </code>
     *
     * @param     mixed $opIngresso The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByOpIngresso($opIngresso = null, $comparison = null)
    {
        if (is_array($opIngresso)) {
            $useMinMax = false;
            if (isset($opIngresso['min'])) {
                $this->addUsingAlias(TbloadalunoPeer::OP_INGRESSO, $opIngresso['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($opIngresso['max'])) {
                $this->addUsingAlias(TbloadalunoPeer::OP_INGRESSO, $opIngresso['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::OP_INGRESSO, $opIngresso, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(TbloadalunoPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(TbloadalunoPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(TbloadalunoPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(TbloadalunoPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query on the created_by column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedBy('fooValue');   // WHERE created_by = 'fooValue'
     * $query->filterByCreatedBy('%fooValue%'); // WHERE created_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $createdBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByCreatedBy($createdBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($createdBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $createdBy)) {
                $createdBy = str_replace('*', '%', $createdBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::CREATED_BY, $createdBy, $comparison);
    }

    /**
     * Filter the query on the updated_by column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedBy('fooValue');   // WHERE updated_by = 'fooValue'
     * $query->filterByUpdatedBy('%fooValue%'); // WHERE updated_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $updatedBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function filterByUpdatedBy($updatedBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($updatedBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $updatedBy)) {
                $updatedBy = str_replace('*', '%', $updatedBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbloadalunoPeer::UPDATED_BY, $updatedBy, $comparison);
    }

    /**
     * Filter the query by a related Tbcursoversao object
     *
     * @param   Tbcursoversao|PropelObjectCollection $tbcursoversao The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   TbloadalunoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTbcursoversao($tbcursoversao, $comparison = null)
    {
        if ($tbcursoversao instanceof Tbcursoversao) {
            return $this
                ->addUsingAlias(TbloadalunoPeer::ID_VERSAO_CURSO, $tbcursoversao->getIdVersaoCurso(), $comparison);
        } elseif ($tbcursoversao instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(TbloadalunoPeer::ID_VERSAO_CURSO, $tbcursoversao->toKeyValue('PrimaryKey', 'IdVersaoCurso'), $comparison);
        } else {
            throw new PropelException('filterByTbcursoversao() only accepts arguments of type Tbcursoversao or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Tbcursoversao relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function joinTbcursoversao($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Tbcursoversao');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Tbcursoversao');
        }

        return $this;
    }

    /**
     * Use the Tbcursoversao relation Tbcursoversao object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TbcursoversaoQuery A secondary query class using the current class as primary query
     */
    public function useTbcursoversaoQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinTbcursoversao($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Tbcursoversao', 'TbcursoversaoQuery');
    }

    /**
     * Filter the query by a related Tbtipoingresso object
     *
     * @param   Tbtipoingresso|PropelObjectCollection $tbtipoingresso The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   TbloadalunoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTbtipoingresso($tbtipoingresso, $comparison = null)
    {
        if ($tbtipoingresso instanceof Tbtipoingresso) {
            return $this
                ->addUsingAlias(TbloadalunoPeer::ID_TIPO_INGRESSO, $tbtipoingresso->getIdTipoIngresso(), $comparison);
        } elseif ($tbtipoingresso instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(TbloadalunoPeer::ID_TIPO_INGRESSO, $tbtipoingresso->toKeyValue('PrimaryKey', 'IdTipoIngresso'), $comparison);
        } else {
            throw new PropelException('filterByTbtipoingresso() only accepts arguments of type Tbtipoingresso or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Tbtipoingresso relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function joinTbtipoingresso($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Tbtipoingresso');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Tbtipoingresso');
        }

        return $this;
    }

    /**
     * Use the Tbtipoingresso relation Tbtipoingresso object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TbtipoingressoQuery A secondary query class using the current class as primary query
     */
    public function useTbtipoingressoQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinTbtipoingresso($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Tbtipoingresso', 'TbtipoingressoQuery');
    }

    /**
     * Filter the query by a related Tbalunosituacao object
     *
     * @param   Tbalunosituacao|PropelObjectCollection $tbalunosituacao The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   TbloadalunoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTbalunosituacao($tbalunosituacao, $comparison = null)
    {
        if ($tbalunosituacao instanceof Tbalunosituacao) {
            return $this
                ->addUsingAlias(TbloadalunoPeer::ID_SITUACAO, $tbalunosituacao->getIdSituacao(), $comparison);
        } elseif ($tbalunosituacao instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(TbloadalunoPeer::ID_SITUACAO, $tbalunosituacao->toKeyValue('PrimaryKey', 'IdSituacao'), $comparison);
        } else {
            throw new PropelException('filterByTbalunosituacao() only accepts arguments of type Tbalunosituacao or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Tbalunosituacao relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function joinTbalunosituacao($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Tbalunosituacao');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Tbalunosituacao');
        }

        return $this;
    }

    /**
     * Use the Tbalunosituacao relation Tbalunosituacao object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TbalunosituacaoQuery A secondary query class using the current class as primary query
     */
    public function useTbalunosituacaoQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinTbalunosituacao($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Tbalunosituacao', 'TbalunosituacaoQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Tbloadaluno $tbloadaluno Object to remove from the list of results
     *
     * @return TbloadalunoQuery The current query, for fluid interface
     */
    public function prune($tbloadaluno = null)
    {
        if ($tbloadaluno) {
            $this->addUsingAlias(TbloadalunoPeer::MATRICULA, $tbloadaluno->getMatricula(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
