<?php

/**
 * Base class that represents a row from the 'tbturma' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Mar 16 17:38:55 2015
 *
 * @package    lib.model.om
 */
abstract class BaseTbturma extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TbturmaPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_turma field.
	 * @var        int
	 */
	protected $id_turma;

	/**
	 * The value for the id_periodo field.
	 * @var        int
	 */
	protected $id_periodo;

	/**
	 * The value for the cod_disciplina field.
	 * @var        string
	 */
	protected $cod_disciplina;

	/**
	 * The value for the turma field.
	 * @var        string
	 */
	protected $turma;

	/**
	 * The value for the n_notas field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $n_notas;

	/**
	 * The value for the observacao field.
	 * @var        string
	 */
	protected $observacao;

	/**
	 * The value for the notas_no_historico field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $notas_no_historico;

	/**
	 * The value for the id_oferta field.
	 * @var        int
	 */
	protected $id_oferta;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the created_by field.
	 * @var        string
	 */
	protected $created_by;

	/**
	 * The value for the updated_by field.
	 * @var        string
	 */
	protected $updated_by;

	/**
	 * @var        Tbperiodo
	 */
	protected $aTbperiodo;

	/**
	 * @var        Tbdisciplina
	 */
	protected $aTbdisciplina;

	/**
	 * @var        Tboferta
	 */
	protected $aTboferta;

	/**
	 * @var        array TbturmaAluno[] Collection to store aggregation of TbturmaAluno objects.
	 */
	protected $collTbturmaAlunos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTbturmaAlunos.
	 */
	private $lastTbturmaAlunoCriteria = null;

	/**
	 * @var        array TbturmaProfessor[] Collection to store aggregation of TbturmaProfessor objects.
	 */
	protected $collTbturmaProfessors;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTbturmaProfessors.
	 */
	private $lastTbturmaProfessorCriteria = null;

	/**
	 * @var        array TbturmaSumula[] Collection to store aggregation of TbturmaSumula objects.
	 */
	protected $collTbturmaSumulas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTbturmaSumulas.
	 */
	private $lastTbturmaSumulaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TbturmaPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->n_notas = 1;
		$this->notas_no_historico = false;
	}

	/**
	 * Initializes internal state of BaseTbturma object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id_turma] column value.
	 * 
	 * @return     int
	 */
	public function getIdTurma()
	{
		return $this->id_turma;
	}

	/**
	 * Get the [id_periodo] column value.
	 * 
	 * @return     int
	 */
	public function getIdPeriodo()
	{
		return $this->id_periodo;
	}

	/**
	 * Get the [cod_disciplina] column value.
	 * 
	 * @return     string
	 */
	public function getCodDisciplina()
	{
		return $this->cod_disciplina;
	}

	/**
	 * Get the [turma] column value.
	 * 
	 * @return     string
	 */
	public function getTurma()
	{
		return $this->turma;
	}

	/**
	 * Get the [n_notas] column value.
	 * 
	 * @return     int
	 */
	public function getNNotas()
	{
		return $this->n_notas;
	}

	/**
	 * Get the [observacao] column value.
	 * 
	 * @return     string
	 */
	public function getObservacao()
	{
		return $this->observacao;
	}

	/**
	 * Get the [notas_no_historico] column value.
	 * 
	 * @return     boolean
	 */
	public function getNotasNoHistorico()
	{
		return $this->notas_no_historico;
	}

	/**
	 * Get the [id_oferta] column value.
	 * 
	 * @return     int
	 */
	public function getIdOferta()
	{
		return $this->id_oferta;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [created_by] column value.
	 * 
	 * @return     string
	 */
	public function getCreatedBy()
	{
		return $this->created_by;
	}

	/**
	 * Get the [updated_by] column value.
	 * 
	 * @return     string
	 */
	public function getUpdatedBy()
	{
		return $this->updated_by;
	}

	/**
	 * Set the value of [id_turma] column.
	 * 
	 * @param      int $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setIdTurma($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_turma !== $v) {
			$this->id_turma = $v;
			$this->modifiedColumns[] = TbturmaPeer::ID_TURMA;
		}

		return $this;
	} // setIdTurma()

	/**
	 * Set the value of [id_periodo] column.
	 * 
	 * @param      int $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setIdPeriodo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_periodo !== $v) {
			$this->id_periodo = $v;
			$this->modifiedColumns[] = TbturmaPeer::ID_PERIODO;
		}

		if ($this->aTbperiodo !== null && $this->aTbperiodo->getIdPeriodo() !== $v) {
			$this->aTbperiodo = null;
		}

		return $this;
	} // setIdPeriodo()

	/**
	 * Set the value of [cod_disciplina] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setCodDisciplina($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cod_disciplina !== $v) {
			$this->cod_disciplina = $v;
			$this->modifiedColumns[] = TbturmaPeer::COD_DISCIPLINA;
		}

		if ($this->aTbdisciplina !== null && $this->aTbdisciplina->getCodDisciplina() !== $v) {
			$this->aTbdisciplina = null;
		}

		return $this;
	} // setCodDisciplina()

	/**
	 * Set the value of [turma] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setTurma($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->turma !== $v) {
			$this->turma = $v;
			$this->modifiedColumns[] = TbturmaPeer::TURMA;
		}

		return $this;
	} // setTurma()

	/**
	 * Set the value of [n_notas] column.
	 * 
	 * @param      int $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setNNotas($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->n_notas !== $v || $this->isNew()) {
			$this->n_notas = $v;
			$this->modifiedColumns[] = TbturmaPeer::N_NOTAS;
		}

		return $this;
	} // setNNotas()

	/**
	 * Set the value of [observacao] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setObservacao($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->observacao !== $v) {
			$this->observacao = $v;
			$this->modifiedColumns[] = TbturmaPeer::OBSERVACAO;
		}

		return $this;
	} // setObservacao()

	/**
	 * Set the value of [notas_no_historico] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setNotasNoHistorico($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->notas_no_historico !== $v || $this->isNew()) {
			$this->notas_no_historico = $v;
			$this->modifiedColumns[] = TbturmaPeer::NOTAS_NO_HISTORICO;
		}

		return $this;
	} // setNotasNoHistorico()

	/**
	 * Set the value of [id_oferta] column.
	 * 
	 * @param      int $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setIdOferta($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_oferta !== $v) {
			$this->id_oferta = $v;
			$this->modifiedColumns[] = TbturmaPeer::ID_OFERTA;
		}

		if ($this->aTboferta !== null && $this->aTboferta->getIdOferta() !== $v) {
			$this->aTboferta = null;
		}

		return $this;
	} // setIdOferta()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = TbturmaPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = TbturmaPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [created_by] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setCreatedBy($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->created_by !== $v) {
			$this->created_by = $v;
			$this->modifiedColumns[] = TbturmaPeer::CREATED_BY;
		}

		return $this;
	} // setCreatedBy()

	/**
	 * Set the value of [updated_by] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbturma The current object (for fluent API support)
	 */
	public function setUpdatedBy($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->updated_by !== $v) {
			$this->updated_by = $v;
			$this->modifiedColumns[] = TbturmaPeer::UPDATED_BY;
		}

		return $this;
	} // setUpdatedBy()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->n_notas !== 1) {
				return false;
			}

			if ($this->notas_no_historico !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_turma = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_periodo = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->cod_disciplina = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->turma = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->n_notas = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->observacao = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->notas_no_historico = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
			$this->id_oferta = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->updated_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->created_by = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->updated_by = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = TbturmaPeer::NUM_COLUMNS - TbturmaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tbturma object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTbperiodo !== null && $this->id_periodo !== $this->aTbperiodo->getIdPeriodo()) {
			$this->aTbperiodo = null;
		}
		if ($this->aTbdisciplina !== null && $this->cod_disciplina !== $this->aTbdisciplina->getCodDisciplina()) {
			$this->aTbdisciplina = null;
		}
		if ($this->aTboferta !== null && $this->id_oferta !== $this->aTboferta->getIdOferta()) {
			$this->aTboferta = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TbturmaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TbturmaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTbperiodo = null;
			$this->aTbdisciplina = null;
			$this->aTboferta = null;
			$this->collTbturmaAlunos = null;
			$this->lastTbturmaAlunoCriteria = null;

			$this->collTbturmaProfessors = null;
			$this->lastTbturmaProfessorCriteria = null;

			$this->collTbturmaSumulas = null;
			$this->lastTbturmaSumulaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TbturmaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTbturma:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				TbturmaPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTbturma:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TbturmaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTbturma:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(TbturmaPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(TbturmaPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTbturma:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				TbturmaPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTbperiodo !== null) {
				if ($this->aTbperiodo->isModified() || $this->aTbperiodo->isNew()) {
					$affectedRows += $this->aTbperiodo->save($con);
				}
				$this->setTbperiodo($this->aTbperiodo);
			}

			if ($this->aTbdisciplina !== null) {
				if ($this->aTbdisciplina->isModified() || $this->aTbdisciplina->isNew()) {
					$affectedRows += $this->aTbdisciplina->save($con);
				}
				$this->setTbdisciplina($this->aTbdisciplina);
			}

			if ($this->aTboferta !== null) {
				if ($this->aTboferta->isModified() || $this->aTboferta->isNew()) {
					$affectedRows += $this->aTboferta->save($con);
				}
				$this->setTboferta($this->aTboferta);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TbturmaPeer::ID_TURMA;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TbturmaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdTurma($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TbturmaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTbturmaAlunos !== null) {
				foreach ($this->collTbturmaAlunos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTbturmaProfessors !== null) {
				foreach ($this->collTbturmaProfessors as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTbturmaSumulas !== null) {
				foreach ($this->collTbturmaSumulas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTbperiodo !== null) {
				if (!$this->aTbperiodo->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTbperiodo->getValidationFailures());
				}
			}

			if ($this->aTbdisciplina !== null) {
				if (!$this->aTbdisciplina->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTbdisciplina->getValidationFailures());
				}
			}

			if ($this->aTboferta !== null) {
				if (!$this->aTboferta->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTboferta->getValidationFailures());
				}
			}


			if (($retval = TbturmaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTbturmaAlunos !== null) {
					foreach ($this->collTbturmaAlunos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTbturmaProfessors !== null) {
					foreach ($this->collTbturmaProfessors as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTbturmaSumulas !== null) {
					foreach ($this->collTbturmaSumulas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TbturmaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdTurma();
				break;
			case 1:
				return $this->getIdPeriodo();
				break;
			case 2:
				return $this->getCodDisciplina();
				break;
			case 3:
				return $this->getTurma();
				break;
			case 4:
				return $this->getNNotas();
				break;
			case 5:
				return $this->getObservacao();
				break;
			case 6:
				return $this->getNotasNoHistorico();
				break;
			case 7:
				return $this->getIdOferta();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getUpdatedAt();
				break;
			case 10:
				return $this->getCreatedBy();
				break;
			case 11:
				return $this->getUpdatedBy();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TbturmaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdTurma(),
			$keys[1] => $this->getIdPeriodo(),
			$keys[2] => $this->getCodDisciplina(),
			$keys[3] => $this->getTurma(),
			$keys[4] => $this->getNNotas(),
			$keys[5] => $this->getObservacao(),
			$keys[6] => $this->getNotasNoHistorico(),
			$keys[7] => $this->getIdOferta(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getUpdatedAt(),
			$keys[10] => $this->getCreatedBy(),
			$keys[11] => $this->getUpdatedBy(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TbturmaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdTurma($value);
				break;
			case 1:
				$this->setIdPeriodo($value);
				break;
			case 2:
				$this->setCodDisciplina($value);
				break;
			case 3:
				$this->setTurma($value);
				break;
			case 4:
				$this->setNNotas($value);
				break;
			case 5:
				$this->setObservacao($value);
				break;
			case 6:
				$this->setNotasNoHistorico($value);
				break;
			case 7:
				$this->setIdOferta($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setUpdatedAt($value);
				break;
			case 10:
				$this->setCreatedBy($value);
				break;
			case 11:
				$this->setUpdatedBy($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TbturmaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdTurma($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdPeriodo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCodDisciplina($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTurma($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNNotas($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setObservacao($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setNotasNoHistorico($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setIdOferta($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUpdatedAt($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCreatedBy($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUpdatedBy($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);

		if ($this->isColumnModified(TbturmaPeer::ID_TURMA)) $criteria->add(TbturmaPeer::ID_TURMA, $this->id_turma);
		if ($this->isColumnModified(TbturmaPeer::ID_PERIODO)) $criteria->add(TbturmaPeer::ID_PERIODO, $this->id_periodo);
		if ($this->isColumnModified(TbturmaPeer::COD_DISCIPLINA)) $criteria->add(TbturmaPeer::COD_DISCIPLINA, $this->cod_disciplina);
		if ($this->isColumnModified(TbturmaPeer::TURMA)) $criteria->add(TbturmaPeer::TURMA, $this->turma);
		if ($this->isColumnModified(TbturmaPeer::N_NOTAS)) $criteria->add(TbturmaPeer::N_NOTAS, $this->n_notas);
		if ($this->isColumnModified(TbturmaPeer::OBSERVACAO)) $criteria->add(TbturmaPeer::OBSERVACAO, $this->observacao);
		if ($this->isColumnModified(TbturmaPeer::NOTAS_NO_HISTORICO)) $criteria->add(TbturmaPeer::NOTAS_NO_HISTORICO, $this->notas_no_historico);
		if ($this->isColumnModified(TbturmaPeer::ID_OFERTA)) $criteria->add(TbturmaPeer::ID_OFERTA, $this->id_oferta);
		if ($this->isColumnModified(TbturmaPeer::CREATED_AT)) $criteria->add(TbturmaPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(TbturmaPeer::UPDATED_AT)) $criteria->add(TbturmaPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(TbturmaPeer::CREATED_BY)) $criteria->add(TbturmaPeer::CREATED_BY, $this->created_by);
		if ($this->isColumnModified(TbturmaPeer::UPDATED_BY)) $criteria->add(TbturmaPeer::UPDATED_BY, $this->updated_by);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);

		$criteria->add(TbturmaPeer::ID_TURMA, $this->id_turma);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdTurma();
	}

	/**
	 * Generic method to set the primary key (id_turma column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdTurma($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tbturma (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdPeriodo($this->id_periodo);

		$copyObj->setCodDisciplina($this->cod_disciplina);

		$copyObj->setTurma($this->turma);

		$copyObj->setNNotas($this->n_notas);

		$copyObj->setObservacao($this->observacao);

		$copyObj->setNotasNoHistorico($this->notas_no_historico);

		$copyObj->setIdOferta($this->id_oferta);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setCreatedBy($this->created_by);

		$copyObj->setUpdatedBy($this->updated_by);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTbturmaAlunos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTbturmaAluno($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTbturmaProfessors() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTbturmaProfessor($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTbturmaSumulas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTbturmaSumula($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdTurma(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tbturma Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TbturmaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TbturmaPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Tbperiodo object.
	 *
	 * @param      Tbperiodo $v
	 * @return     Tbturma The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTbperiodo(Tbperiodo $v = null)
	{
		if ($v === null) {
			$this->setIdPeriodo(NULL);
		} else {
			$this->setIdPeriodo($v->getIdPeriodo());
		}

		$this->aTbperiodo = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tbperiodo object, it will not be re-added.
		if ($v !== null) {
			$v->addTbturma($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tbperiodo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tbperiodo The associated Tbperiodo object.
	 * @throws     PropelException
	 */
	public function getTbperiodo(PropelPDO $con = null)
	{
		if ($this->aTbperiodo === null && ($this->id_periodo !== null)) {
			$this->aTbperiodo = TbperiodoPeer::retrieveByPk($this->id_periodo);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTbperiodo->addTbturmas($this);
			 */
		}
		return $this->aTbperiodo;
	}

	/**
	 * Declares an association between this object and a Tbdisciplina object.
	 *
	 * @param      Tbdisciplina $v
	 * @return     Tbturma The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTbdisciplina(Tbdisciplina $v = null)
	{
		if ($v === null) {
			$this->setCodDisciplina(NULL);
		} else {
			$this->setCodDisciplina($v->getCodDisciplina());
		}

		$this->aTbdisciplina = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tbdisciplina object, it will not be re-added.
		if ($v !== null) {
			$v->addTbturma($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tbdisciplina object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tbdisciplina The associated Tbdisciplina object.
	 * @throws     PropelException
	 */
	public function getTbdisciplina(PropelPDO $con = null)
	{
		if ($this->aTbdisciplina === null && (($this->cod_disciplina !== "" && $this->cod_disciplina !== null))) {
			$this->aTbdisciplina = TbdisciplinaPeer::retrieveByPk($this->cod_disciplina);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTbdisciplina->addTbturmas($this);
			 */
		}
		return $this->aTbdisciplina;
	}

	/**
	 * Declares an association between this object and a Tboferta object.
	 *
	 * @param      Tboferta $v
	 * @return     Tbturma The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTboferta(Tboferta $v = null)
	{
		if ($v === null) {
			$this->setIdOferta(NULL);
		} else {
			$this->setIdOferta($v->getIdOferta());
		}

		$this->aTboferta = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tboferta object, it will not be re-added.
		if ($v !== null) {
			$v->addTbturma($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tboferta object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tboferta The associated Tboferta object.
	 * @throws     PropelException
	 */
	public function getTboferta(PropelPDO $con = null)
	{
		if ($this->aTboferta === null && ($this->id_oferta !== null)) {
			$this->aTboferta = TbofertaPeer::retrieveByPk($this->id_oferta);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTboferta->addTbturmas($this);
			 */
		}
		return $this->aTboferta;
	}

	/**
	 * Clears out the collTbturmaAlunos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTbturmaAlunos()
	 */
	public function clearTbturmaAlunos()
	{
		$this->collTbturmaAlunos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTbturmaAlunos collection (array).
	 *
	 * By default this just sets the collTbturmaAlunos collection to an empty array (like clearcollTbturmaAlunos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTbturmaAlunos()
	{
		$this->collTbturmaAlunos = array();
	}

	/**
	 * Gets an array of TbturmaAluno objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tbturma has previously been saved, it will retrieve
	 * related TbturmaAlunos from storage. If this Tbturma is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TbturmaAluno[]
	 * @throws     PropelException
	 */
	public function getTbturmaAlunos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbturmaAlunos === null) {
			if ($this->isNew()) {
			   $this->collTbturmaAlunos = array();
			} else {

				$criteria->add(TbturmaAlunoPeer::ID_TURMA, $this->id_turma);

				TbturmaAlunoPeer::addSelectColumns($criteria);
				$this->collTbturmaAlunos = TbturmaAlunoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TbturmaAlunoPeer::ID_TURMA, $this->id_turma);

				TbturmaAlunoPeer::addSelectColumns($criteria);
				if (!isset($this->lastTbturmaAlunoCriteria) || !$this->lastTbturmaAlunoCriteria->equals($criteria)) {
					$this->collTbturmaAlunos = TbturmaAlunoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTbturmaAlunoCriteria = $criteria;
		return $this->collTbturmaAlunos;
	}

	/**
	 * Returns the number of related TbturmaAluno objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TbturmaAluno objects.
	 * @throws     PropelException
	 */
	public function countTbturmaAlunos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTbturmaAlunos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TbturmaAlunoPeer::ID_TURMA, $this->id_turma);

				$count = TbturmaAlunoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TbturmaAlunoPeer::ID_TURMA, $this->id_turma);

				if (!isset($this->lastTbturmaAlunoCriteria) || !$this->lastTbturmaAlunoCriteria->equals($criteria)) {
					$count = TbturmaAlunoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTbturmaAlunos);
				}
			} else {
				$count = count($this->collTbturmaAlunos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TbturmaAluno object to this object
	 * through the TbturmaAluno foreign key attribute.
	 *
	 * @param      TbturmaAluno $l TbturmaAluno
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTbturmaAluno(TbturmaAluno $l)
	{
		if ($this->collTbturmaAlunos === null) {
			$this->initTbturmaAlunos();
		}
		if (!in_array($l, $this->collTbturmaAlunos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTbturmaAlunos, $l);
			$l->setTbturma($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbturma is new, it will return
	 * an empty collection; or if this Tbturma has previously
	 * been saved, it will retrieve related TbturmaAlunos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbturma.
	 */
	public function getTbturmaAlunosJoinTbaluno($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbturmaAlunos === null) {
			if ($this->isNew()) {
				$this->collTbturmaAlunos = array();
			} else {

				$criteria->add(TbturmaAlunoPeer::ID_TURMA, $this->id_turma);

				$this->collTbturmaAlunos = TbturmaAlunoPeer::doSelectJoinTbaluno($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TbturmaAlunoPeer::ID_TURMA, $this->id_turma);

			if (!isset($this->lastTbturmaAlunoCriteria) || !$this->lastTbturmaAlunoCriteria->equals($criteria)) {
				$this->collTbturmaAlunos = TbturmaAlunoPeer::doSelectJoinTbaluno($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbturmaAlunoCriteria = $criteria;

		return $this->collTbturmaAlunos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbturma is new, it will return
	 * an empty collection; or if this Tbturma has previously
	 * been saved, it will retrieve related TbturmaAlunos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbturma.
	 */
	public function getTbturmaAlunosJoinTbconceito($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbturmaAlunos === null) {
			if ($this->isNew()) {
				$this->collTbturmaAlunos = array();
			} else {

				$criteria->add(TbturmaAlunoPeer::ID_TURMA, $this->id_turma);

				$this->collTbturmaAlunos = TbturmaAlunoPeer::doSelectJoinTbconceito($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TbturmaAlunoPeer::ID_TURMA, $this->id_turma);

			if (!isset($this->lastTbturmaAlunoCriteria) || !$this->lastTbturmaAlunoCriteria->equals($criteria)) {
				$this->collTbturmaAlunos = TbturmaAlunoPeer::doSelectJoinTbconceito($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbturmaAlunoCriteria = $criteria;

		return $this->collTbturmaAlunos;
	}

	/**
	 * Clears out the collTbturmaProfessors collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTbturmaProfessors()
	 */
	public function clearTbturmaProfessors()
	{
		$this->collTbturmaProfessors = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTbturmaProfessors collection (array).
	 *
	 * By default this just sets the collTbturmaProfessors collection to an empty array (like clearcollTbturmaProfessors());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTbturmaProfessors()
	{
		$this->collTbturmaProfessors = array();
	}

	/**
	 * Gets an array of TbturmaProfessor objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tbturma has previously been saved, it will retrieve
	 * related TbturmaProfessors from storage. If this Tbturma is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TbturmaProfessor[]
	 * @throws     PropelException
	 */
	public function getTbturmaProfessors($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbturmaProfessors === null) {
			if ($this->isNew()) {
			   $this->collTbturmaProfessors = array();
			} else {

				$criteria->add(TbturmaProfessorPeer::ID_TURMA, $this->id_turma);

				TbturmaProfessorPeer::addSelectColumns($criteria);
				$this->collTbturmaProfessors = TbturmaProfessorPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TbturmaProfessorPeer::ID_TURMA, $this->id_turma);

				TbturmaProfessorPeer::addSelectColumns($criteria);
				if (!isset($this->lastTbturmaProfessorCriteria) || !$this->lastTbturmaProfessorCriteria->equals($criteria)) {
					$this->collTbturmaProfessors = TbturmaProfessorPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTbturmaProfessorCriteria = $criteria;
		return $this->collTbturmaProfessors;
	}

	/**
	 * Returns the number of related TbturmaProfessor objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TbturmaProfessor objects.
	 * @throws     PropelException
	 */
	public function countTbturmaProfessors(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTbturmaProfessors === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TbturmaProfessorPeer::ID_TURMA, $this->id_turma);

				$count = TbturmaProfessorPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TbturmaProfessorPeer::ID_TURMA, $this->id_turma);

				if (!isset($this->lastTbturmaProfessorCriteria) || !$this->lastTbturmaProfessorCriteria->equals($criteria)) {
					$count = TbturmaProfessorPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTbturmaProfessors);
				}
			} else {
				$count = count($this->collTbturmaProfessors);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TbturmaProfessor object to this object
	 * through the TbturmaProfessor foreign key attribute.
	 *
	 * @param      TbturmaProfessor $l TbturmaProfessor
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTbturmaProfessor(TbturmaProfessor $l)
	{
		if ($this->collTbturmaProfessors === null) {
			$this->initTbturmaProfessors();
		}
		if (!in_array($l, $this->collTbturmaProfessors, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTbturmaProfessors, $l);
			$l->setTbturma($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbturma is new, it will return
	 * an empty collection; or if this Tbturma has previously
	 * been saved, it will retrieve related TbturmaProfessors from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbturma.
	 */
	public function getTbturmaProfessorsJoinTbprofessor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbturmaProfessors === null) {
			if ($this->isNew()) {
				$this->collTbturmaProfessors = array();
			} else {

				$criteria->add(TbturmaProfessorPeer::ID_TURMA, $this->id_turma);

				$this->collTbturmaProfessors = TbturmaProfessorPeer::doSelectJoinTbprofessor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TbturmaProfessorPeer::ID_TURMA, $this->id_turma);

			if (!isset($this->lastTbturmaProfessorCriteria) || !$this->lastTbturmaProfessorCriteria->equals($criteria)) {
				$this->collTbturmaProfessors = TbturmaProfessorPeer::doSelectJoinTbprofessor($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbturmaProfessorCriteria = $criteria;

		return $this->collTbturmaProfessors;
	}

	/**
	 * Clears out the collTbturmaSumulas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTbturmaSumulas()
	 */
	public function clearTbturmaSumulas()
	{
		$this->collTbturmaSumulas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTbturmaSumulas collection (array).
	 *
	 * By default this just sets the collTbturmaSumulas collection to an empty array (like clearcollTbturmaSumulas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTbturmaSumulas()
	{
		$this->collTbturmaSumulas = array();
	}

	/**
	 * Gets an array of TbturmaSumula objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tbturma has previously been saved, it will retrieve
	 * related TbturmaSumulas from storage. If this Tbturma is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TbturmaSumula[]
	 * @throws     PropelException
	 */
	public function getTbturmaSumulas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbturmaSumulas === null) {
			if ($this->isNew()) {
			   $this->collTbturmaSumulas = array();
			} else {

				$criteria->add(TbturmaSumulaPeer::ID_TURMA, $this->id_turma);

				TbturmaSumulaPeer::addSelectColumns($criteria);
				$this->collTbturmaSumulas = TbturmaSumulaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TbturmaSumulaPeer::ID_TURMA, $this->id_turma);

				TbturmaSumulaPeer::addSelectColumns($criteria);
				if (!isset($this->lastTbturmaSumulaCriteria) || !$this->lastTbturmaSumulaCriteria->equals($criteria)) {
					$this->collTbturmaSumulas = TbturmaSumulaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTbturmaSumulaCriteria = $criteria;
		return $this->collTbturmaSumulas;
	}

	/**
	 * Returns the number of related TbturmaSumula objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TbturmaSumula objects.
	 * @throws     PropelException
	 */
	public function countTbturmaSumulas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbturmaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTbturmaSumulas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TbturmaSumulaPeer::ID_TURMA, $this->id_turma);

				$count = TbturmaSumulaPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TbturmaSumulaPeer::ID_TURMA, $this->id_turma);

				if (!isset($this->lastTbturmaSumulaCriteria) || !$this->lastTbturmaSumulaCriteria->equals($criteria)) {
					$count = TbturmaSumulaPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTbturmaSumulas);
				}
			} else {
				$count = count($this->collTbturmaSumulas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TbturmaSumula object to this object
	 * through the TbturmaSumula foreign key attribute.
	 *
	 * @param      TbturmaSumula $l TbturmaSumula
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTbturmaSumula(TbturmaSumula $l)
	{
		if ($this->collTbturmaSumulas === null) {
			$this->initTbturmaSumulas();
		}
		if (!in_array($l, $this->collTbturmaSumulas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTbturmaSumulas, $l);
			$l->setTbturma($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTbturmaAlunos) {
				foreach ((array) $this->collTbturmaAlunos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTbturmaProfessors) {
				foreach ((array) $this->collTbturmaProfessors as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTbturmaSumulas) {
				foreach ((array) $this->collTbturmaSumulas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTbturmaAlunos = null;
		$this->collTbturmaProfessors = null;
		$this->collTbturmaSumulas = null;
			$this->aTbperiodo = null;
			$this->aTbdisciplina = null;
			$this->aTboferta = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTbturma:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTbturma::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTbturma
