<?php

/**
 * Base class that represents a row from the 'tbcampus' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Mar 16 17:38:50 2015
 *
 * @package    lib.model.om
 */
abstract class BaseTbcampus extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TbcampusPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_campus field.
	 * @var        int
	 */
	protected $id_campus;

	/**
	 * The value for the descricao field.
	 * @var        string
	 */
	protected $descricao;

	/**
	 * The value for the id_cidade field.
	 * @var        string
	 */
	protected $id_cidade;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the created_by field.
	 * @var        string
	 */
	protected $created_by;

	/**
	 * The value for the updated_by field.
	 * @var        string
	 */
	protected $updated_by;

	/**
	 * @var        Tbcidade
	 */
	protected $aTbcidade;

	/**
	 * @var        array Tbcursoversao[] Collection to store aggregation of Tbcursoversao objects.
	 */
	protected $collTbcursoversaos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTbcursoversaos.
	 */
	private $lastTbcursoversaoCriteria = null;

	/**
	 * @var        array Tbsala[] Collection to store aggregation of Tbsala objects.
	 */
	protected $collTbsalas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTbsalas.
	 */
	private $lastTbsalaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TbcampusPeer';

	/**
	 * Get the [id_campus] column value.
	 * 
	 * @return     int
	 */
	public function getIdCampus()
	{
		return $this->id_campus;
	}

	/**
	 * Get the [descricao] column value.
	 * 
	 * @return     string
	 */
	public function getDescricao()
	{
		return $this->descricao;
	}

	/**
	 * Get the [id_cidade] column value.
	 * 
	 * @return     string
	 */
	public function getIdCidade()
	{
		return $this->id_cidade;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [created_by] column value.
	 * 
	 * @return     string
	 */
	public function getCreatedBy()
	{
		return $this->created_by;
	}

	/**
	 * Get the [updated_by] column value.
	 * 
	 * @return     string
	 */
	public function getUpdatedBy()
	{
		return $this->updated_by;
	}

	/**
	 * Set the value of [id_campus] column.
	 * 
	 * @param      int $v new value
	 * @return     Tbcampus The current object (for fluent API support)
	 */
	public function setIdCampus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_campus !== $v) {
			$this->id_campus = $v;
			$this->modifiedColumns[] = TbcampusPeer::ID_CAMPUS;
		}

		return $this;
	} // setIdCampus()

	/**
	 * Set the value of [descricao] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbcampus The current object (for fluent API support)
	 */
	public function setDescricao($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descricao !== $v) {
			$this->descricao = $v;
			$this->modifiedColumns[] = TbcampusPeer::DESCRICAO;
		}

		return $this;
	} // setDescricao()

	/**
	 * Set the value of [id_cidade] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbcampus The current object (for fluent API support)
	 */
	public function setIdCidade($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id_cidade !== $v) {
			$this->id_cidade = $v;
			$this->modifiedColumns[] = TbcampusPeer::ID_CIDADE;
		}

		if ($this->aTbcidade !== null && $this->aTbcidade->getIdCidade() !== $v) {
			$this->aTbcidade = null;
		}

		return $this;
	} // setIdCidade()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tbcampus The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = TbcampusPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Tbcampus The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = TbcampusPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [created_by] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbcampus The current object (for fluent API support)
	 */
	public function setCreatedBy($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->created_by !== $v) {
			$this->created_by = $v;
			$this->modifiedColumns[] = TbcampusPeer::CREATED_BY;
		}

		return $this;
	} // setCreatedBy()

	/**
	 * Set the value of [updated_by] column.
	 * 
	 * @param      string $v new value
	 * @return     Tbcampus The current object (for fluent API support)
	 */
	public function setUpdatedBy($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->updated_by !== $v) {
			$this->updated_by = $v;
			$this->modifiedColumns[] = TbcampusPeer::UPDATED_BY;
		}

		return $this;
	} // setUpdatedBy()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_campus = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->descricao = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->id_cidade = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->created_at = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->updated_at = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->created_by = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->updated_by = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = TbcampusPeer::NUM_COLUMNS - TbcampusPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tbcampus object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTbcidade !== null && $this->id_cidade !== $this->aTbcidade->getIdCidade()) {
			$this->aTbcidade = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TbcampusPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TbcampusPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTbcidade = null;
			$this->collTbcursoversaos = null;
			$this->lastTbcursoversaoCriteria = null;

			$this->collTbsalas = null;
			$this->lastTbsalaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TbcampusPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTbcampus:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				TbcampusPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTbcampus:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TbcampusPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTbcampus:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(TbcampusPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(TbcampusPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTbcampus:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				TbcampusPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTbcidade !== null) {
				if ($this->aTbcidade->isModified() || $this->aTbcidade->isNew()) {
					$affectedRows += $this->aTbcidade->save($con);
				}
				$this->setTbcidade($this->aTbcidade);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TbcampusPeer::ID_CAMPUS;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TbcampusPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdCampus($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TbcampusPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTbcursoversaos !== null) {
				foreach ($this->collTbcursoversaos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTbsalas !== null) {
				foreach ($this->collTbsalas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTbcidade !== null) {
				if (!$this->aTbcidade->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTbcidade->getValidationFailures());
				}
			}


			if (($retval = TbcampusPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTbcursoversaos !== null) {
					foreach ($this->collTbcursoversaos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTbsalas !== null) {
					foreach ($this->collTbsalas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TbcampusPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdCampus();
				break;
			case 1:
				return $this->getDescricao();
				break;
			case 2:
				return $this->getIdCidade();
				break;
			case 3:
				return $this->getCreatedAt();
				break;
			case 4:
				return $this->getUpdatedAt();
				break;
			case 5:
				return $this->getCreatedBy();
				break;
			case 6:
				return $this->getUpdatedBy();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TbcampusPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdCampus(),
			$keys[1] => $this->getDescricao(),
			$keys[2] => $this->getIdCidade(),
			$keys[3] => $this->getCreatedAt(),
			$keys[4] => $this->getUpdatedAt(),
			$keys[5] => $this->getCreatedBy(),
			$keys[6] => $this->getUpdatedBy(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TbcampusPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdCampus($value);
				break;
			case 1:
				$this->setDescricao($value);
				break;
			case 2:
				$this->setIdCidade($value);
				break;
			case 3:
				$this->setCreatedAt($value);
				break;
			case 4:
				$this->setUpdatedAt($value);
				break;
			case 5:
				$this->setCreatedBy($value);
				break;
			case 6:
				$this->setUpdatedBy($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TbcampusPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdCampus($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDescricao($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdCidade($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCreatedAt($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setUpdatedAt($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCreatedBy($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUpdatedBy($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);

		if ($this->isColumnModified(TbcampusPeer::ID_CAMPUS)) $criteria->add(TbcampusPeer::ID_CAMPUS, $this->id_campus);
		if ($this->isColumnModified(TbcampusPeer::DESCRICAO)) $criteria->add(TbcampusPeer::DESCRICAO, $this->descricao);
		if ($this->isColumnModified(TbcampusPeer::ID_CIDADE)) $criteria->add(TbcampusPeer::ID_CIDADE, $this->id_cidade);
		if ($this->isColumnModified(TbcampusPeer::CREATED_AT)) $criteria->add(TbcampusPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(TbcampusPeer::UPDATED_AT)) $criteria->add(TbcampusPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(TbcampusPeer::CREATED_BY)) $criteria->add(TbcampusPeer::CREATED_BY, $this->created_by);
		if ($this->isColumnModified(TbcampusPeer::UPDATED_BY)) $criteria->add(TbcampusPeer::UPDATED_BY, $this->updated_by);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);

		$criteria->add(TbcampusPeer::ID_CAMPUS, $this->id_campus);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdCampus();
	}

	/**
	 * Generic method to set the primary key (id_campus column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdCampus($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tbcampus (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDescricao($this->descricao);

		$copyObj->setIdCidade($this->id_cidade);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setCreatedBy($this->created_by);

		$copyObj->setUpdatedBy($this->updated_by);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTbcursoversaos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTbcursoversao($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTbsalas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTbsala($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdCampus(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tbcampus Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TbcampusPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TbcampusPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Tbcidade object.
	 *
	 * @param      Tbcidade $v
	 * @return     Tbcampus The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTbcidade(Tbcidade $v = null)
	{
		if ($v === null) {
			$this->setIdCidade(NULL);
		} else {
			$this->setIdCidade($v->getIdCidade());
		}

		$this->aTbcidade = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tbcidade object, it will not be re-added.
		if ($v !== null) {
			$v->addTbcampus($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tbcidade object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tbcidade The associated Tbcidade object.
	 * @throws     PropelException
	 */
	public function getTbcidade(PropelPDO $con = null)
	{
		if ($this->aTbcidade === null && (($this->id_cidade !== "" && $this->id_cidade !== null))) {
			$this->aTbcidade = TbcidadePeer::retrieveByPk($this->id_cidade);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTbcidade->addTbcampuss($this);
			 */
		}
		return $this->aTbcidade;
	}

	/**
	 * Clears out the collTbcursoversaos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTbcursoversaos()
	 */
	public function clearTbcursoversaos()
	{
		$this->collTbcursoversaos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTbcursoversaos collection (array).
	 *
	 * By default this just sets the collTbcursoversaos collection to an empty array (like clearcollTbcursoversaos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTbcursoversaos()
	{
		$this->collTbcursoversaos = array();
	}

	/**
	 * Gets an array of Tbcursoversao objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tbcampus has previously been saved, it will retrieve
	 * related Tbcursoversaos from storage. If this Tbcampus is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tbcursoversao[]
	 * @throws     PropelException
	 */
	public function getTbcursoversaos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbcursoversaos === null) {
			if ($this->isNew()) {
			   $this->collTbcursoversaos = array();
			} else {

				$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

				TbcursoversaoPeer::addSelectColumns($criteria);
				$this->collTbcursoversaos = TbcursoversaoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

				TbcursoversaoPeer::addSelectColumns($criteria);
				if (!isset($this->lastTbcursoversaoCriteria) || !$this->lastTbcursoversaoCriteria->equals($criteria)) {
					$this->collTbcursoversaos = TbcursoversaoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTbcursoversaoCriteria = $criteria;
		return $this->collTbcursoversaos;
	}

	/**
	 * Returns the number of related Tbcursoversao objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tbcursoversao objects.
	 * @throws     PropelException
	 */
	public function countTbcursoversaos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTbcursoversaos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

				$count = TbcursoversaoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

				if (!isset($this->lastTbcursoversaoCriteria) || !$this->lastTbcursoversaoCriteria->equals($criteria)) {
					$count = TbcursoversaoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTbcursoversaos);
				}
			} else {
				$count = count($this->collTbcursoversaos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tbcursoversao object to this object
	 * through the Tbcursoversao foreign key attribute.
	 *
	 * @param      Tbcursoversao $l Tbcursoversao
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTbcursoversao(Tbcursoversao $l)
	{
		if ($this->collTbcursoversaos === null) {
			$this->initTbcursoversaos();
		}
		if (!in_array($l, $this->collTbcursoversaos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTbcursoversaos, $l);
			$l->setTbcampus($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbcampus is new, it will return
	 * an empty collection; or if this Tbcampus has previously
	 * been saved, it will retrieve related Tbcursoversaos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbcampus.
	 */
	public function getTbcursoversaosJoinTbformacao($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbcursoversaos === null) {
			if ($this->isNew()) {
				$this->collTbcursoversaos = array();
			} else {

				$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

				$this->collTbcursoversaos = TbcursoversaoPeer::doSelectJoinTbformacao($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

			if (!isset($this->lastTbcursoversaoCriteria) || !$this->lastTbcursoversaoCriteria->equals($criteria)) {
				$this->collTbcursoversaos = TbcursoversaoPeer::doSelectJoinTbformacao($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbcursoversaoCriteria = $criteria;

		return $this->collTbcursoversaos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbcampus is new, it will return
	 * an empty collection; or if this Tbcampus has previously
	 * been saved, it will retrieve related Tbcursoversaos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbcampus.
	 */
	public function getTbcursoversaosJoinTbcurso($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbcursoversaos === null) {
			if ($this->isNew()) {
				$this->collTbcursoversaos = array();
			} else {

				$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

				$this->collTbcursoversaos = TbcursoversaoPeer::doSelectJoinTbcurso($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

			if (!isset($this->lastTbcursoversaoCriteria) || !$this->lastTbcursoversaoCriteria->equals($criteria)) {
				$this->collTbcursoversaos = TbcursoversaoPeer::doSelectJoinTbcurso($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbcursoversaoCriteria = $criteria;

		return $this->collTbcursoversaos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbcampus is new, it will return
	 * an empty collection; or if this Tbcampus has previously
	 * been saved, it will retrieve related Tbcursoversaos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbcampus.
	 */
	public function getTbcursoversaosJoinTbturno($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbcursoversaos === null) {
			if ($this->isNew()) {
				$this->collTbcursoversaos = array();
			} else {

				$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

				$this->collTbcursoversaos = TbcursoversaoPeer::doSelectJoinTbturno($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

			if (!isset($this->lastTbcursoversaoCriteria) || !$this->lastTbcursoversaoCriteria->equals($criteria)) {
				$this->collTbcursoversaos = TbcursoversaoPeer::doSelectJoinTbturno($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbcursoversaoCriteria = $criteria;

		return $this->collTbcursoversaos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Tbcampus is new, it will return
	 * an empty collection; or if this Tbcampus has previously
	 * been saved, it will retrieve related Tbcursoversaos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Tbcampus.
	 */
	public function getTbcursoversaosJoinTbsetor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbcursoversaos === null) {
			if ($this->isNew()) {
				$this->collTbcursoversaos = array();
			} else {

				$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

				$this->collTbcursoversaos = TbcursoversaoPeer::doSelectJoinTbsetor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TbcursoversaoPeer::ID_CAMPUS, $this->id_campus);

			if (!isset($this->lastTbcursoversaoCriteria) || !$this->lastTbcursoversaoCriteria->equals($criteria)) {
				$this->collTbcursoversaos = TbcursoversaoPeer::doSelectJoinTbsetor($criteria, $con, $join_behavior);
			}
		}
		$this->lastTbcursoversaoCriteria = $criteria;

		return $this->collTbcursoversaos;
	}

	/**
	 * Clears out the collTbsalas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTbsalas()
	 */
	public function clearTbsalas()
	{
		$this->collTbsalas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTbsalas collection (array).
	 *
	 * By default this just sets the collTbsalas collection to an empty array (like clearcollTbsalas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTbsalas()
	{
		$this->collTbsalas = array();
	}

	/**
	 * Gets an array of Tbsala objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Tbcampus has previously been saved, it will retrieve
	 * related Tbsalas from storage. If this Tbcampus is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tbsala[]
	 * @throws     PropelException
	 */
	public function getTbsalas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTbsalas === null) {
			if ($this->isNew()) {
			   $this->collTbsalas = array();
			} else {

				$criteria->add(TbsalaPeer::ID_CAMPUS, $this->id_campus);

				TbsalaPeer::addSelectColumns($criteria);
				$this->collTbsalas = TbsalaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TbsalaPeer::ID_CAMPUS, $this->id_campus);

				TbsalaPeer::addSelectColumns($criteria);
				if (!isset($this->lastTbsalaCriteria) || !$this->lastTbsalaCriteria->equals($criteria)) {
					$this->collTbsalas = TbsalaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTbsalaCriteria = $criteria;
		return $this->collTbsalas;
	}

	/**
	 * Returns the number of related Tbsala objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tbsala objects.
	 * @throws     PropelException
	 */
	public function countTbsalas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TbcampusPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTbsalas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TbsalaPeer::ID_CAMPUS, $this->id_campus);

				$count = TbsalaPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TbsalaPeer::ID_CAMPUS, $this->id_campus);

				if (!isset($this->lastTbsalaCriteria) || !$this->lastTbsalaCriteria->equals($criteria)) {
					$count = TbsalaPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTbsalas);
				}
			} else {
				$count = count($this->collTbsalas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tbsala object to this object
	 * through the Tbsala foreign key attribute.
	 *
	 * @param      Tbsala $l Tbsala
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTbsala(Tbsala $l)
	{
		if ($this->collTbsalas === null) {
			$this->initTbsalas();
		}
		if (!in_array($l, $this->collTbsalas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTbsalas, $l);
			$l->setTbcampus($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTbcursoversaos) {
				foreach ((array) $this->collTbcursoversaos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTbsalas) {
				foreach ((array) $this->collTbsalas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTbcursoversaos = null;
		$this->collTbsalas = null;
			$this->aTbcidade = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTbcampus:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTbcampus::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTbcampus
