<?php


/**
 * Base class that represents a query for the 'tbpessoa' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Apr 23 17:54:39 2013
 *
 * @method TbpessoaQuery orderByIdPessoa($order = Criteria::ASC) Order by the id_pessoa column
 * @method TbpessoaQuery orderByNome($order = Criteria::ASC) Order by the nome column
 * @method TbpessoaQuery orderByCelular($order = Criteria::ASC) Order by the celular column
 * @method TbpessoaQuery orderByEmail($order = Criteria::ASC) Order by the email column
 * @method TbpessoaQuery orderByFoneResidencial($order = Criteria::ASC) Order by the fone_residencial column
 * @method TbpessoaQuery orderByFoto($order = Criteria::ASC) Order by the foto column
 * @method TbpessoaQuery orderByIdNecesEspecial($order = Criteria::ASC) Order by the id_neces_especial column
 * @method TbpessoaQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method TbpessoaQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method TbpessoaQuery orderByCreatedBy($order = Criteria::ASC) Order by the created_by column
 * @method TbpessoaQuery orderByUpdatedBy($order = Criteria::ASC) Order by the updated_by column
 *
 * @method TbpessoaQuery groupByIdPessoa() Group by the id_pessoa column
 * @method TbpessoaQuery groupByNome() Group by the nome column
 * @method TbpessoaQuery groupByCelular() Group by the celular column
 * @method TbpessoaQuery groupByEmail() Group by the email column
 * @method TbpessoaQuery groupByFoneResidencial() Group by the fone_residencial column
 * @method TbpessoaQuery groupByFoto() Group by the foto column
 * @method TbpessoaQuery groupByIdNecesEspecial() Group by the id_neces_especial column
 * @method TbpessoaQuery groupByCreatedAt() Group by the created_at column
 * @method TbpessoaQuery groupByUpdatedAt() Group by the updated_at column
 * @method TbpessoaQuery groupByCreatedBy() Group by the created_by column
 * @method TbpessoaQuery groupByUpdatedBy() Group by the updated_by column
 *
 * @method TbpessoaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method TbpessoaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method TbpessoaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method TbpessoaQuery leftJoinTbnecesespecial($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tbnecesespecial relation
 * @method TbpessoaQuery rightJoinTbnecesespecial($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tbnecesespecial relation
 * @method TbpessoaQuery innerJoinTbnecesespecial($relationAlias = null) Adds a INNER JOIN clause to the query using the Tbnecesespecial relation
 *
 * @method Tbpessoa findOne(PropelPDO $con = null) Return the first Tbpessoa matching the query
 * @method Tbpessoa findOneOrCreate(PropelPDO $con = null) Return the first Tbpessoa matching the query, or a new Tbpessoa object populated from the query conditions when no match is found
 *
 * @method Tbpessoa findOneByIdPessoa(int $id_pessoa) Return the first Tbpessoa filtered by the id_pessoa column
 * @method Tbpessoa findOneByNome(string $nome) Return the first Tbpessoa filtered by the nome column
 * @method Tbpessoa findOneByCelular(string $celular) Return the first Tbpessoa filtered by the celular column
 * @method Tbpessoa findOneByEmail(string $email) Return the first Tbpessoa filtered by the email column
 * @method Tbpessoa findOneByFoneResidencial(string $fone_residencial) Return the first Tbpessoa filtered by the fone_residencial column
 * @method Tbpessoa findOneByFoto(resource $foto) Return the first Tbpessoa filtered by the foto column
 * @method Tbpessoa findOneByIdNecesEspecial(string $id_neces_especial) Return the first Tbpessoa filtered by the id_neces_especial column
 * @method Tbpessoa findOneByCreatedAt(string $created_at) Return the first Tbpessoa filtered by the created_at column
 * @method Tbpessoa findOneByUpdatedAt(string $updated_at) Return the first Tbpessoa filtered by the updated_at column
 * @method Tbpessoa findOneByCreatedBy(string $created_by) Return the first Tbpessoa filtered by the created_by column
 * @method Tbpessoa findOneByUpdatedBy(string $updated_by) Return the first Tbpessoa filtered by the updated_by column
 *
 * @method array findByIdPessoa(int $id_pessoa) Return Tbpessoa objects filtered by the id_pessoa column
 * @method array findByNome(string $nome) Return Tbpessoa objects filtered by the nome column
 * @method array findByCelular(string $celular) Return Tbpessoa objects filtered by the celular column
 * @method array findByEmail(string $email) Return Tbpessoa objects filtered by the email column
 * @method array findByFoneResidencial(string $fone_residencial) Return Tbpessoa objects filtered by the fone_residencial column
 * @method array findByFoto(resource $foto) Return Tbpessoa objects filtered by the foto column
 * @method array findByIdNecesEspecial(string $id_neces_especial) Return Tbpessoa objects filtered by the id_neces_especial column
 * @method array findByCreatedAt(string $created_at) Return Tbpessoa objects filtered by the created_at column
 * @method array findByUpdatedAt(string $updated_at) Return Tbpessoa objects filtered by the updated_at column
 * @method array findByCreatedBy(string $created_by) Return Tbpessoa objects filtered by the created_by column
 * @method array findByUpdatedBy(string $updated_by) Return Tbpessoa objects filtered by the updated_by column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTbpessoaQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseTbpessoaQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Tbpessoa', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new TbpessoaQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     TbpessoaQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return TbpessoaQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof TbpessoaQuery) {
            return $criteria;
        }
        $query = new TbpessoaQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Tbpessoa|Tbpessoa[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = TbpessoaPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(TbpessoaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Tbpessoa A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT ID_PESSOA, NOME, CELULAR, EMAIL, FONE_RESIDENCIAL, FOTO, ID_NECES_ESPECIAL, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY FROM tbpessoa WHERE ID_PESSOA = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Tbpessoa();
            $obj->hydrate($row);
            TbpessoaPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Tbpessoa|Tbpessoa[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Tbpessoa[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(TbpessoaPeer::ID_PESSOA, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(TbpessoaPeer::ID_PESSOA, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id_pessoa column
     *
     * Example usage:
     * <code>
     * $query->filterByIdPessoa(1234); // WHERE id_pessoa = 1234
     * $query->filterByIdPessoa(array(12, 34)); // WHERE id_pessoa IN (12, 34)
     * $query->filterByIdPessoa(array('min' => 12)); // WHERE id_pessoa > 12
     * </code>
     *
     * @param     mixed $idPessoa The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByIdPessoa($idPessoa = null, $comparison = null)
    {
        if (is_array($idPessoa) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(TbpessoaPeer::ID_PESSOA, $idPessoa, $comparison);
    }

    /**
     * Filter the query on the nome column
     *
     * Example usage:
     * <code>
     * $query->filterByNome('fooValue');   // WHERE nome = 'fooValue'
     * $query->filterByNome('%fooValue%'); // WHERE nome LIKE '%fooValue%'
     * </code>
     *
     * @param     string $nome The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByNome($nome = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($nome)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $nome)) {
                $nome = str_replace('*', '%', $nome);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::NOME, $nome, $comparison);
    }

    /**
     * Filter the query on the celular column
     *
     * Example usage:
     * <code>
     * $query->filterByCelular('fooValue');   // WHERE celular = 'fooValue'
     * $query->filterByCelular('%fooValue%'); // WHERE celular LIKE '%fooValue%'
     * </code>
     *
     * @param     string $celular The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByCelular($celular = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($celular)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $celular)) {
                $celular = str_replace('*', '%', $celular);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::CELULAR, $celular, $comparison);
    }

    /**
     * Filter the query on the email column
     *
     * Example usage:
     * <code>
     * $query->filterByEmail('fooValue');   // WHERE email = 'fooValue'
     * $query->filterByEmail('%fooValue%'); // WHERE email LIKE '%fooValue%'
     * </code>
     *
     * @param     string $email The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByEmail($email = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($email)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $email)) {
                $email = str_replace('*', '%', $email);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::EMAIL, $email, $comparison);
    }

    /**
     * Filter the query on the fone_residencial column
     *
     * Example usage:
     * <code>
     * $query->filterByFoneResidencial('fooValue');   // WHERE fone_residencial = 'fooValue'
     * $query->filterByFoneResidencial('%fooValue%'); // WHERE fone_residencial LIKE '%fooValue%'
     * </code>
     *
     * @param     string $foneResidencial The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByFoneResidencial($foneResidencial = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($foneResidencial)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $foneResidencial)) {
                $foneResidencial = str_replace('*', '%', $foneResidencial);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::FONE_RESIDENCIAL, $foneResidencial, $comparison);
    }

    /**
     * Filter the query on the foto column
     *
     * @param     mixed $foto The value to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByFoto($foto = null, $comparison = null)
    {

        return $this->addUsingAlias(TbpessoaPeer::FOTO, $foto, $comparison);
    }

    /**
     * Filter the query on the id_neces_especial column
     *
     * Example usage:
     * <code>
     * $query->filterByIdNecesEspecial('fooValue');   // WHERE id_neces_especial = 'fooValue'
     * $query->filterByIdNecesEspecial('%fooValue%'); // WHERE id_neces_especial LIKE '%fooValue%'
     * </code>
     *
     * @param     string $idNecesEspecial The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByIdNecesEspecial($idNecesEspecial = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($idNecesEspecial)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $idNecesEspecial)) {
                $idNecesEspecial = str_replace('*', '%', $idNecesEspecial);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::ID_NECES_ESPECIAL, $idNecesEspecial, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(TbpessoaPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(TbpessoaPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(TbpessoaPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(TbpessoaPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query on the created_by column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedBy('fooValue');   // WHERE created_by = 'fooValue'
     * $query->filterByCreatedBy('%fooValue%'); // WHERE created_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $createdBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByCreatedBy($createdBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($createdBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $createdBy)) {
                $createdBy = str_replace('*', '%', $createdBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::CREATED_BY, $createdBy, $comparison);
    }

    /**
     * Filter the query on the updated_by column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedBy('fooValue');   // WHERE updated_by = 'fooValue'
     * $query->filterByUpdatedBy('%fooValue%'); // WHERE updated_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $updatedBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function filterByUpdatedBy($updatedBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($updatedBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $updatedBy)) {
                $updatedBy = str_replace('*', '%', $updatedBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbpessoaPeer::UPDATED_BY, $updatedBy, $comparison);
    }

    /**
     * Filter the query by a related Tbnecesespecial object
     *
     * @param   Tbnecesespecial|PropelObjectCollection $tbnecesespecial The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   TbpessoaQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTbnecesespecial($tbnecesespecial, $comparison = null)
    {
        if ($tbnecesespecial instanceof Tbnecesespecial) {
            return $this
                ->addUsingAlias(TbpessoaPeer::ID_NECES_ESPECIAL, $tbnecesespecial->getIdNecesEspecial(), $comparison);
        } elseif ($tbnecesespecial instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(TbpessoaPeer::ID_NECES_ESPECIAL, $tbnecesespecial->toKeyValue('PrimaryKey', 'IdNecesEspecial'), $comparison);
        } else {
            throw new PropelException('filterByTbnecesespecial() only accepts arguments of type Tbnecesespecial or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Tbnecesespecial relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function joinTbnecesespecial($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Tbnecesespecial');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Tbnecesespecial');
        }

        return $this;
    }

    /**
     * Use the Tbnecesespecial relation Tbnecesespecial object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TbnecesespecialQuery A secondary query class using the current class as primary query
     */
    public function useTbnecesespecialQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinTbnecesespecial($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Tbnecesespecial', 'TbnecesespecialQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Tbpessoa $tbpessoa Object to remove from the list of results
     *
     * @return TbpessoaQuery The current query, for fluid interface
     */
    public function prune($tbpessoa = null)
    {
        if ($tbpessoa) {
            $this->addUsingAlias(TbpessoaPeer::ID_PESSOA, $tbpessoa->getIdPessoa(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
