<?php


/**
 * Base class that represents a query for the 'tbmatriculacomprovante' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Apr 23 17:54:36 2013
 *
 * @method TbmatriculaComprovanteQuery orderByIdComprovante($order = Criteria::ASC) Order by the id_comprovante column
 * @method TbmatriculaComprovanteQuery orderByMatricula($order = Criteria::ASC) Order by the matricula column
 * @method TbmatriculaComprovanteQuery orderByDataHora($order = Criteria::ASC) Order by the datahora column
 * @method TbmatriculaComprovanteQuery orderByCodigo($order = Criteria::ASC) Order by the codigo column
 * @method TbmatriculaComprovanteQuery orderBySituacao($order = Criteria::ASC) Order by the situacao column
 * @method TbmatriculaComprovanteQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method TbmatriculaComprovanteQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method TbmatriculaComprovanteQuery orderByCreatedBy($order = Criteria::ASC) Order by the created_by column
 * @method TbmatriculaComprovanteQuery orderByUpdatedBy($order = Criteria::ASC) Order by the updated_by column
 *
 * @method TbmatriculaComprovanteQuery groupByIdComprovante() Group by the id_comprovante column
 * @method TbmatriculaComprovanteQuery groupByMatricula() Group by the matricula column
 * @method TbmatriculaComprovanteQuery groupByDataHora() Group by the datahora column
 * @method TbmatriculaComprovanteQuery groupByCodigo() Group by the codigo column
 * @method TbmatriculaComprovanteQuery groupBySituacao() Group by the situacao column
 * @method TbmatriculaComprovanteQuery groupByCreatedAt() Group by the created_at column
 * @method TbmatriculaComprovanteQuery groupByUpdatedAt() Group by the updated_at column
 * @method TbmatriculaComprovanteQuery groupByCreatedBy() Group by the created_by column
 * @method TbmatriculaComprovanteQuery groupByUpdatedBy() Group by the updated_by column
 *
 * @method TbmatriculaComprovanteQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method TbmatriculaComprovanteQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method TbmatriculaComprovanteQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method TbmatriculaComprovanteQuery leftJoinTbalunomatricula($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tbalunomatricula relation
 * @method TbmatriculaComprovanteQuery rightJoinTbalunomatricula($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tbalunomatricula relation
 * @method TbmatriculaComprovanteQuery innerJoinTbalunomatricula($relationAlias = null) Adds a INNER JOIN clause to the query using the Tbalunomatricula relation
 *
 * @method TbmatriculaComprovante findOne(PropelPDO $con = null) Return the first TbmatriculaComprovante matching the query
 * @method TbmatriculaComprovante findOneOrCreate(PropelPDO $con = null) Return the first TbmatriculaComprovante matching the query, or a new TbmatriculaComprovante object populated from the query conditions when no match is found
 *
 * @method TbmatriculaComprovante findOneByIdComprovante(int $id_comprovante) Return the first TbmatriculaComprovante filtered by the id_comprovante column
 * @method TbmatriculaComprovante findOneByMatricula(string $matricula) Return the first TbmatriculaComprovante filtered by the matricula column
 * @method TbmatriculaComprovante findOneByDataHora(string $datahora) Return the first TbmatriculaComprovante filtered by the datahora column
 * @method TbmatriculaComprovante findOneByCodigo(string $codigo) Return the first TbmatriculaComprovante filtered by the codigo column
 * @method TbmatriculaComprovante findOneBySituacao(string $situacao) Return the first TbmatriculaComprovante filtered by the situacao column
 * @method TbmatriculaComprovante findOneByCreatedAt(string $created_at) Return the first TbmatriculaComprovante filtered by the created_at column
 * @method TbmatriculaComprovante findOneByUpdatedAt(string $updated_at) Return the first TbmatriculaComprovante filtered by the updated_at column
 * @method TbmatriculaComprovante findOneByCreatedBy(string $created_by) Return the first TbmatriculaComprovante filtered by the created_by column
 * @method TbmatriculaComprovante findOneByUpdatedBy(string $updated_by) Return the first TbmatriculaComprovante filtered by the updated_by column
 *
 * @method array findByIdComprovante(int $id_comprovante) Return TbmatriculaComprovante objects filtered by the id_comprovante column
 * @method array findByMatricula(string $matricula) Return TbmatriculaComprovante objects filtered by the matricula column
 * @method array findByDataHora(string $datahora) Return TbmatriculaComprovante objects filtered by the datahora column
 * @method array findByCodigo(string $codigo) Return TbmatriculaComprovante objects filtered by the codigo column
 * @method array findBySituacao(string $situacao) Return TbmatriculaComprovante objects filtered by the situacao column
 * @method array findByCreatedAt(string $created_at) Return TbmatriculaComprovante objects filtered by the created_at column
 * @method array findByUpdatedAt(string $updated_at) Return TbmatriculaComprovante objects filtered by the updated_at column
 * @method array findByCreatedBy(string $created_by) Return TbmatriculaComprovante objects filtered by the created_by column
 * @method array findByUpdatedBy(string $updated_by) Return TbmatriculaComprovante objects filtered by the updated_by column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTbmatriculaComprovanteQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseTbmatriculaComprovanteQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'TbmatriculaComprovante', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new TbmatriculaComprovanteQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     TbmatriculaComprovanteQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return TbmatriculaComprovanteQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof TbmatriculaComprovanteQuery) {
            return $criteria;
        }
        $query = new TbmatriculaComprovanteQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   TbmatriculaComprovante|TbmatriculaComprovante[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = TbmatriculaComprovantePeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(TbmatriculaComprovantePeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   TbmatriculaComprovante A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT ID_COMPROVANTE, MATRICULA, DATAHORA, CODIGO, SITUACAO, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY FROM tbmatriculacomprovante WHERE ID_COMPROVANTE = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new TbmatriculaComprovante();
            $obj->hydrate($row);
            TbmatriculaComprovantePeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return TbmatriculaComprovante|TbmatriculaComprovante[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|TbmatriculaComprovante[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(TbmatriculaComprovantePeer::ID_COMPROVANTE, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(TbmatriculaComprovantePeer::ID_COMPROVANTE, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id_comprovante column
     *
     * Example usage:
     * <code>
     * $query->filterByIdComprovante(1234); // WHERE id_comprovante = 1234
     * $query->filterByIdComprovante(array(12, 34)); // WHERE id_comprovante IN (12, 34)
     * $query->filterByIdComprovante(array('min' => 12)); // WHERE id_comprovante > 12
     * </code>
     *
     * @param     mixed $idComprovante The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByIdComprovante($idComprovante = null, $comparison = null)
    {
        if (is_array($idComprovante) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::ID_COMPROVANTE, $idComprovante, $comparison);
    }

    /**
     * Filter the query on the matricula column
     *
     * Example usage:
     * <code>
     * $query->filterByMatricula(1234); // WHERE matricula = 1234
     * $query->filterByMatricula(array(12, 34)); // WHERE matricula IN (12, 34)
     * $query->filterByMatricula(array('min' => 12)); // WHERE matricula > 12
     * </code>
     *
     * @see       filterByTbalunomatricula()
     *
     * @param     mixed $matricula The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByMatricula($matricula = null, $comparison = null)
    {
        if (is_array($matricula)) {
            $useMinMax = false;
            if (isset($matricula['min'])) {
                $this->addUsingAlias(TbmatriculaComprovantePeer::MATRICULA, $matricula['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($matricula['max'])) {
                $this->addUsingAlias(TbmatriculaComprovantePeer::MATRICULA, $matricula['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::MATRICULA, $matricula, $comparison);
    }

    /**
     * Filter the query on the datahora column
     *
     * Example usage:
     * <code>
     * $query->filterByDataHora('2011-03-14'); // WHERE datahora = '2011-03-14'
     * $query->filterByDataHora('now'); // WHERE datahora = '2011-03-14'
     * $query->filterByDataHora(array('max' => 'yesterday')); // WHERE datahora > '2011-03-13'
     * </code>
     *
     * @param     mixed $dataHora The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByDataHora($dataHora = null, $comparison = null)
    {
        if (is_array($dataHora)) {
            $useMinMax = false;
            if (isset($dataHora['min'])) {
                $this->addUsingAlias(TbmatriculaComprovantePeer::DATAHORA, $dataHora['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($dataHora['max'])) {
                $this->addUsingAlias(TbmatriculaComprovantePeer::DATAHORA, $dataHora['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::DATAHORA, $dataHora, $comparison);
    }

    /**
     * Filter the query on the codigo column
     *
     * Example usage:
     * <code>
     * $query->filterByCodigo('fooValue');   // WHERE codigo = 'fooValue'
     * $query->filterByCodigo('%fooValue%'); // WHERE codigo LIKE '%fooValue%'
     * </code>
     *
     * @param     string $codigo The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByCodigo($codigo = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($codigo)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $codigo)) {
                $codigo = str_replace('*', '%', $codigo);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::CODIGO, $codigo, $comparison);
    }

    /**
     * Filter the query on the situacao column
     *
     * Example usage:
     * <code>
     * $query->filterBySituacao('fooValue');   // WHERE situacao = 'fooValue'
     * $query->filterBySituacao('%fooValue%'); // WHERE situacao LIKE '%fooValue%'
     * </code>
     *
     * @param     string $situacao The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterBySituacao($situacao = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($situacao)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $situacao)) {
                $situacao = str_replace('*', '%', $situacao);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::SITUACAO, $situacao, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(TbmatriculaComprovantePeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(TbmatriculaComprovantePeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(TbmatriculaComprovantePeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(TbmatriculaComprovantePeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query on the created_by column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedBy('fooValue');   // WHERE created_by = 'fooValue'
     * $query->filterByCreatedBy('%fooValue%'); // WHERE created_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $createdBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByCreatedBy($createdBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($createdBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $createdBy)) {
                $createdBy = str_replace('*', '%', $createdBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::CREATED_BY, $createdBy, $comparison);
    }

    /**
     * Filter the query on the updated_by column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedBy('fooValue');   // WHERE updated_by = 'fooValue'
     * $query->filterByUpdatedBy('%fooValue%'); // WHERE updated_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $updatedBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function filterByUpdatedBy($updatedBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($updatedBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $updatedBy)) {
                $updatedBy = str_replace('*', '%', $updatedBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TbmatriculaComprovantePeer::UPDATED_BY, $updatedBy, $comparison);
    }

    /**
     * Filter the query by a related Tbalunomatricula object
     *
     * @param   Tbalunomatricula|PropelObjectCollection $tbalunomatricula The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   TbmatriculaComprovanteQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTbalunomatricula($tbalunomatricula, $comparison = null)
    {
        if ($tbalunomatricula instanceof Tbalunomatricula) {
            return $this
                ->addUsingAlias(TbmatriculaComprovantePeer::MATRICULA, $tbalunomatricula->getMatricula(), $comparison);
        } elseif ($tbalunomatricula instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(TbmatriculaComprovantePeer::MATRICULA, $tbalunomatricula->toKeyValue('PrimaryKey', 'Matricula'), $comparison);
        } else {
            throw new PropelException('filterByTbalunomatricula() only accepts arguments of type Tbalunomatricula or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Tbalunomatricula relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function joinTbalunomatricula($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Tbalunomatricula');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Tbalunomatricula');
        }

        return $this;
    }

    /**
     * Use the Tbalunomatricula relation Tbalunomatricula object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TbalunomatriculaQuery A secondary query class using the current class as primary query
     */
    public function useTbalunomatriculaQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinTbalunomatricula($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Tbalunomatricula', 'TbalunomatriculaQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   TbmatriculaComprovante $tbmatriculaComprovante Object to remove from the list of results
     *
     * @return TbmatriculaComprovanteQuery The current query, for fluid interface
     */
    public function prune($tbmatriculaComprovante = null)
    {
        if ($tbmatriculaComprovante) {
            $this->addUsingAlias(TbmatriculaComprovantePeer::ID_COMPROVANTE, $tbmatriculaComprovante->getIdComprovante(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
