generator:
  class: sfPropelGenerator
  param:
    model_class:           tbcidade
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tbcidade
    plural:                tbcidades
    route_prefix:          tbcidade
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=descricao,Tbestado,Tbpais]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
