generator:
  class: sfPropelGenerator
  param:
    model_class:           tbsumula
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tbsumula
    plural:                tbsumulas
    route_prefix:          tbsumula
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
