generator:
  class: sfPropelGenerator
  param:
    model_class:           Tbalunomatricula
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Tbalunomatricula
    plural:                Tbalunomatriculas
    route_prefix:          tbalunomatricula
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: ~
      filter: ~
      form:
        display:
          "NONE": [matricula,id_versao_curso,id_tipo_ingresso,id_polo]
          "Dados Pessoais": [nome,sexo,estado_civil,celular,fone_residencial,id_neces_especial,dt_nascimento,nacionalidade,naturalidade,pai,mae,email,id_raca]
          "Documentos": [cpf,rg,rg_org_exped,rg_dt_exped,titulo,titulo_zona,titulo_secao,reservista]
          "Endereço": [cep,numero,complemento]
          "Dados Acadêmicos": [dt_ingresso,id_situacao,dt_situacao,id_2grau,ano_concl_2grau]
        fields:
          id_tipo_ingresso: {label: 'Tipo de Ingresso'}
          id_raca: {label: 'Raca/Cor'}
          dt_nascimento: {label: 'Data de Nascimento'}
          id_trabalho: {label: Instituição}
          cep_trabalho: {label: CEP}
          fone_trabalho: {label: Telefone}
          id_2grau: {label: Instituição de 2º Grau }
          ramal_trabalho: {label: Ramal}
      edit:    ~
      new:
        fields:
          matricula: {help: "Valor formado por: ano e semestre de ingresso, código do curso e posição no vestibular" }
