generator:
  class: sfPropelGenerator
  param:
    model_class:           tbsala
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tbsala
    plural:                tbsalas
    route_prefix:          tbsala
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=descricao,numero,bloco,Tbcampus,capacidade]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
