<?php


/**
 * Skeleton subclass for representing a row from the 'radcheck' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Feb  4 09:39:55 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class HotSpotRadcheck extends BaseHotSpotRadcheck {

    /**
     * Initializes internal state of HotSpotRadcheck object.
     * @see        parent::__construct()
     */
    public function __construct() {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
        $this->setAttribute('MD5-Password');
        $this->setOp(':=');
    }

}

// HotSpotRadcheck
