<?php


/**
 * Skeleton subclass for representing a row from the 'tbaluno_racacor' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Thu Apr 14 10:07:55 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tbalunoracacor extends BaseTbalunoracacor {
    
    public function __toString() {
        return $this->getDescricao();
    }
    
    public function save(PropelPDO $con = null) {
        Log::save($this);
        parent::save($con);
    }

} // Tbalunoracacor
