<?php


/**
 * Skeleton subclass for representing a row from the 'tbalunomatricula' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Tue Jan  8 17:16:36 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tbalunomatricula extends BaseTbalunomatricula {

	/**
	 * Initializes internal state of Tbalunomatricula object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // Tbalunomatricula
