<?php


/**
 * Skeleton subclass for representing a row from the 'tbaviso_local' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sun May 16 23:16:40 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TbavisoLocal extends BaseTbavisoLocal {
    public function __toString() {
        return $this->descricao;
    }

         public function save(PropelPDO $con = null) {
        Log::save($this);
        parent::save($con);
    }
} // TbavisoLocal
