<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tbcursonivel' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Jan 10 11:51:39 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TbcursonivelPeer extends BaseTbcursonivelPeer {

    public static function retrieveArrayByCriteria($criteria){
        $array =  array();
        $nivel = new tbcursonivel();
        foreach (TbcursonivelPeer::doSelect($criteria) as $nivel){
            $array[] = $nivel->getIdNivel();
        }

        return $array;
    }

} // TbcursonivelPeer
