<?php


/**
 * Skeleton subclass for representing a row from the 'tbdocs' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri May  9 10:52:55 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tbdocs extends BaseTbdocs {

} // Tbdocs
