<?php


/**
 * Skeleton subclass for representing a row from the 'tbloadfile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Feb 21 16:11:02 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tbloadfile extends BaseTbloadfile {

    public function save(PropelPDO $con = null) {
        Log::save($this);
        parent::save($con);
    }

} // Tbloadfile
