<?php


/**
 * Skeleton subclass for representing a row from the 'tbofertahorario' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Tue May  4 12:14:41 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tbofertahorario extends BaseTbofertahorario {

    private $dias_semana = array(
            1 => 'Segunda',
            2 => 'Terca',
            3 => 'Quarta',
            4 => 'Quinta',
            5 => 'Sexta',
            6 => 'Sabado',
            7 => 'Domingo'
    );
    
    function getDiaNome() {
        return $this->dias_semana[$this->dia];
    }

    public function __toString() {
        return $this->getDiaNome().", ".$this->getHoraInicio('H:i').' - '.$this->getHoraFim('H:i');
    }

          public function save(PropelPDO $con = null) {
        Log::save($this);
        parent::save($con);
    }
  } // Tbofertahorario
