<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tbpolos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Apr 25 15:15:56 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TbpolosPeer extends BaseTbpolosPeer {

} // TbpolosPeer
