<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tbreligiao' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Fri Sep 28 11:08:31 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TbreligiaoPeer extends BaseTbreligiaoPeer {

} // TbreligiaoPeer
