<?php

/**
 * Skeleton subclass for performing query and update operations on the 'tbturma_sumula' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sun May 16 18:30:47 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TbturmaSumulaPeer extends BaseTbturmaSumulaPeer {

}

// TbturmaSumulaPeer
