<?php

/**
 * Skeleton subclass for representing a row from the 'tbvalidacao' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Jul 11 10:43:44 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tbvalidacao extends BaseTbvalidacao {

    public function setNumAuth($v) {
        parent::setNumAuth(strtoupper(strrev(hash('crc32b', $this->getId()) . hash('adler32', $this->getId()))));
    }

    public function save(PropelPDO $con = null) {
        Log::save($this);
        parent::save($con);
    }

}

// Tbvalidacao
