dev:
  propel:
    param:
      classname: DebugPDO
      debug: { realmemoryusage: true, details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
test:
  propel:
    param:
      classname: DebugPDO
      dsn: 'pgsql:host=10.0.1.15;dbname=gda'
      username: postgres
      password: postgres

all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'pgsql:host=localhost;dbname=gda'
      username: professor
      password: pr0f@12
      encoding: utf8
      persistent: true
      pooling: true
