generator:
  class: sfPropelGenerator
  param:
    model_class:           tbbairro
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tbbairro
    plural:                tbbairros
    route_prefix:          tbbairro
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=descricao]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
