dev:
  propel:
    param:
      classname: DebugPDO
      debug: { realmemoryusage: true, details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
test:
  propel:
    param:
      classname: DebugPDO
prod:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'pgsql:host=localhost;dbname=gda'
      username: gda2
      password: ZvnmlmlbjZik6
      encoding: utf8
      persistent: true
      pooling: true

  hotspot_aluno:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'pgsql:host=200.129.159.236;dbname=radius'
      username: derca_aluno
      password: AlsBwutA1M
      encoding: utf8
      persistent: true
      pooling: true

  hotspot_professor:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'pgsql:host=200.129.159.236;dbname=radius'
      username: derca_professor
      password: BQZnvCxuj6sWs
      encoding: utf8
      persistent: true
      pooling: true
