all:
  .settings:

    # tempo de sessao
    timeout:     3600

    i18n: true
    default_culture: pt_BR
    default_timezone: America/Boa_Vista


    # jQueryReloadedPlugin
    jquery_web_dir:         /sfJqueryReloadedPlugin
    jquery_core:            jquery-1.4.2.min.js
    jquery_plugin_paths:    /sfJqueryReloadedPlugin/plugins

    cache: on

