generator:
  class: sfPropelGenerator
  param:
    model_class:           tbalunosituacao
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tbalunosituacao
    plural:                tbalunosituacaos
    route_prefix:          tbalunosituacao
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=descricao,sigla_pingifes]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
