<?php

/**
 * Censo2009 filter form base class.
 *
 * @package    derca
 * @subpackage filter
 * @author     George Soon Ho Pereira <george.pereira@ufrr.br>
 * @version    SVN: $Id: sfPropelFormFilterGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BaseCenso2009FormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'aluno_c1'                                       => new sfWidgetFormFilterInput(),
      'aluno_c2'                                       => new sfWidgetFormFilterInput(),
      'aluno_c3'                                       => new sfWidgetFormFilterInput(),
      'aluno_c4_nome'                                  => new sfWidgetFormFilterInput(),
      'aluno_c5_cpf'                                   => new sfWidgetFormFilterInput(),
      'aluno_c6_doc_estrangeiro'                       => new sfWidgetFormFilterInput(),
      'aluno_c7_nascimento'                            => new sfWidgetFormFilterInput(),
      'aluno_c8_sexo'                                  => new sfWidgetFormFilterInput(),
      'aluno_c9_cor_raca'                              => new sfWidgetFormFilterInput(),
      'aluno_c10_mae'                                  => new sfWidgetFormFilterInput(),
      'aluno_c11_nacionalidade'                        => new sfWidgetFormFilterInput(),
      'aluno_c12_uf_nascimento'                        => new sfWidgetFormFilterInput(),
      'aluno_c13_cidade_nascimento'                    => new sfWidgetFormFilterInput(),
      'aluno_c14_pais_origem'                          => new sfWidgetFormFilterInput(),
      'aluno_c15_deficiencia'                          => new sfWidgetFormFilterInput(),
      'aluno_c16_def_cegueria'                         => new sfWidgetFormFilterInput(),
      'aluno_c17_def_baixa_visao'                      => new sfWidgetFormFilterInput(),
      'aluno_c18_def_surdez'                           => new sfWidgetFormFilterInput(),
      'aluno_c19_def_auditiva'                         => new sfWidgetFormFilterInput(),
      'aluno_c20_def_fisica'                           => new sfWidgetFormFilterInput(),
      'aluno_c21_def_surdocegueira'                    => new sfWidgetFormFilterInput(),
      'aluno_c22_def_multipla'                         => new sfWidgetFormFilterInput(),
      'aluno_c23_def_mental'                           => new sfWidgetFormFilterInput(),
      'curso_c1_tipo_reg2'                             => new sfWidgetFormFilterInput(),
      'curso_c2_id_inep_curso'                         => new sfWidgetFormFilterInput(),
      'curso_c3_cod_polo_inep'                         => new sfWidgetFormFilterInput(),
      'curso_c4_turno_aluno'                           => new sfWidgetFormFilterInput(),
      'curso_c5_situacao_vinculo'                      => new sfWidgetFormFilterInput(),
      'curso_c6_data_ingresso'                         => new sfWidgetFormFilterInput(),
      'curso_c7_aluno_publica'                         => new sfWidgetFormFilterInput(),
      'curso_c8_forma_ingresso_selecao_vestibular'     => new sfWidgetFormFilterInput(),
      'curso_c9_forma_ingresso_selecao_enem'           => new sfWidgetFormFilterInput(),
      'curso_c10_forma_ingresso_selecao_outros'        => new sfWidgetFormFilterInput(),
      'curso_c11_forma_ingresso_selecao_pecg'          => new sfWidgetFormFilterInput(),
      'curso_c12_forma_ingresso_outras'                => new sfWidgetFormFilterInput(),
      'curso_c13_programa_reserva_vagas'               => new sfWidgetFormFilterInput(),
      'curso_c14_programa_reserva_vagas'               => new sfWidgetFormFilterInput(),
      'curso_c15_programa_reserva_vagas'               => new sfWidgetFormFilterInput(),
      'curso_c16_programa_reserva_vagas'               => new sfWidgetFormFilterInput(),
      'curso_c17_programa_reserva_vagas'               => new sfWidgetFormFilterInput(),
      'curso_c18_programa_reserva_vagas'               => new sfWidgetFormFilterInput(),
      'curso_c19_financiamento_estudantil'             => new sfWidgetFormFilterInput(),
      'curso_c20_financiamento_estudantil'             => new sfWidgetFormFilterInput(),
      'curso_c21_financiamento_estudantil'             => new sfWidgetFormFilterInput(),
      'curso_c22_financiamento_estudantil'             => new sfWidgetFormFilterInput(),
      'curso_c23_financiamento_estudantil'             => new sfWidgetFormFilterInput(),
      'curso_c24_financiamento_estudantil'             => new sfWidgetFormFilterInput(),
      'curso_c25_financiamento_estudantil'             => new sfWidgetFormFilterInput(),
      'curso_c26_financiamento_estudantil_n_reemb'     => new sfWidgetFormFilterInput(),
      'curso_c27_financiamento_estudantil_n_reemb'     => new sfWidgetFormFilterInput(),
      'curso_c28_financiamento_estudantil_n_reemb'     => new sfWidgetFormFilterInput(),
      'curso_c29_financiamento_estudantil_n_reemb'     => new sfWidgetFormFilterInput(),
      'curso_c30_financiamento_estudantil_n_reemb'     => new sfWidgetFormFilterInput(),
      'curso_c31_financiamento_estudantil_n_reemb'     => new sfWidgetFormFilterInput(),
      'curso_c32_financiamento_estudantil_n_reemb'     => new sfWidgetFormFilterInput(),
      'curso_c33_apoio_social'                         => new sfWidgetFormFilterInput(),
      'curso_c34_tipo_apoio_social'                    => new sfWidgetFormFilterInput(),
      'curso_c35_tipo_apoio_social'                    => new sfWidgetFormFilterInput(),
      'curso_c36_tipo_apoio_social'                    => new sfWidgetFormFilterInput(),
      'curso_c37_tipo_apoio_social'                    => new sfWidgetFormFilterInput(),
      'curso_c38_tipo_apoio_social'                    => new sfWidgetFormFilterInput(),
      'curso_c39_tipo_apoio_social'                    => new sfWidgetFormFilterInput(),
      'curso_c40_atividade_complementar'               => new sfWidgetFormFilterInput(),
      'curso_c41_atividade_complementar'               => new sfWidgetFormFilterInput(),
      'curso_c42_bolsa'                                => new sfWidgetFormFilterInput(),
      'curso_c43_atividade_complementar'               => new sfWidgetFormFilterInput(),
      'curso_c44_bolsa'                                => new sfWidgetFormFilterInput(),
      'curso_c45_atividade_complementar'               => new sfWidgetFormFilterInput(),
      'curso_c46_bolsa'                                => new sfWidgetFormFilterInput(),
      'curso_c47_atividade_complementar'               => new sfWidgetFormFilterInput(),
      'curso_c48_bolsa'                                => new sfWidgetFormFilterInput(),
      'curso_c49_semestre_conclusao'                   => new sfWidgetFormFilterInput(),
      'curso_c50_aluno_parfor'                         => new sfWidgetFormFilterInput(),
      'aluno_c24_def_autismo'                          => new sfWidgetFormFilterInput(),
      'aluno_c25_def_asperger'                         => new sfWidgetFormFilterInput(),
      'aluno_c26_def_rett'                             => new sfWidgetFormFilterInput(),
      'aluno_c27_def_tdi'                              => new sfWidgetFormFilterInput(),
      'aluno_c28_def_superdotado'                      => new sfWidgetFormFilterInput(),
      'curso_c51_semestre_referencia'                  => new sfWidgetFormFilterInput(),
      'curso_c52_curso_origem_transferencia'           => new sfWidgetFormFilterInput(),
      'curso_c53_forma_ingresso_seriada'               => new sfWidgetFormFilterInput(),
      'curso_c54_forma_ingresso_exofficio'             => new sfWidgetFormFilterInput(),
      'curso_c55_forma_ingresso_judicial'              => new sfWidgetFormFilterInput(),
      'curso_c56_mobilidade_academica'                 => new sfWidgetFormFilterInput(),
      'curso_c57_mobilidade_tipo'                      => new sfWidgetFormFilterInput(),
      'curso_c58_mobilidade_ies_destino'               => new sfWidgetFormFilterInput(),
      'curso_c59_mobilidade_tipo_internacional'        => new sfWidgetFormFilterInput(),
      'curso_c60_mobilidade_pais_destino'              => new sfWidgetFormFilterInput(),
      'curso_c61_semestre_ingresso_curso'              => new sfWidgetFormFilterInput(),
      'curso_c62_forma_ingresso_selecao_simples'       => new sfWidgetFormFilterInput(),
      'curso_c63_forma_ingresso_selecao_remanescentes' => new sfWidgetFormFilterInput(),
      'curso_c64_forma_ingresso_selecao_especiais'     => new sfWidgetFormFilterInput(),
      'exportado'                                      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
    ));

    $this->setValidators(array(
      'aluno_c1'                                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aluno_c2'                                       => new sfValidatorPass(array('required' => false)),
      'aluno_c3'                                       => new sfValidatorPass(array('required' => false)),
      'aluno_c4_nome'                                  => new sfValidatorPass(array('required' => false)),
      'aluno_c5_cpf'                                   => new sfValidatorPass(array('required' => false)),
      'aluno_c6_doc_estrangeiro'                       => new sfValidatorPass(array('required' => false)),
      'aluno_c7_nascimento'                            => new sfValidatorPass(array('required' => false)),
      'aluno_c8_sexo'                                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aluno_c9_cor_raca'                              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aluno_c10_mae'                                  => new sfValidatorPass(array('required' => false)),
      'aluno_c11_nacionalidade'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aluno_c12_uf_nascimento'                        => new sfValidatorPass(array('required' => false)),
      'aluno_c13_cidade_nascimento'                    => new sfValidatorPass(array('required' => false)),
      'aluno_c14_pais_origem'                          => new sfValidatorPass(array('required' => false)),
      'aluno_c15_deficiencia'                          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aluno_c16_def_cegueria'                         => new sfValidatorPass(array('required' => false)),
      'aluno_c17_def_baixa_visao'                      => new sfValidatorPass(array('required' => false)),
      'aluno_c18_def_surdez'                           => new sfValidatorPass(array('required' => false)),
      'aluno_c19_def_auditiva'                         => new sfValidatorPass(array('required' => false)),
      'aluno_c20_def_fisica'                           => new sfValidatorPass(array('required' => false)),
      'aluno_c21_def_surdocegueira'                    => new sfValidatorPass(array('required' => false)),
      'aluno_c22_def_multipla'                         => new sfValidatorPass(array('required' => false)),
      'aluno_c23_def_mental'                           => new sfValidatorPass(array('required' => false)),
      'curso_c1_tipo_reg2'                             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c2_id_inep_curso'                         => new sfValidatorPass(array('required' => false)),
      'curso_c3_cod_polo_inep'                         => new sfValidatorPass(array('required' => false)),
      'curso_c4_turno_aluno'                           => new sfValidatorPass(array('required' => false)),
      'curso_c5_situacao_vinculo'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c6_data_ingresso'                         => new sfValidatorPass(array('required' => false)),
      'curso_c7_aluno_publica'                         => new sfValidatorPass(array('required' => false)),
      'curso_c8_forma_ingresso_selecao_vestibular'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c9_forma_ingresso_selecao_enem'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c10_forma_ingresso_selecao_outros'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c11_forma_ingresso_selecao_pecg'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c12_forma_ingresso_outras'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c13_programa_reserva_vagas'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c14_programa_reserva_vagas'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c15_programa_reserva_vagas'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c16_programa_reserva_vagas'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c17_programa_reserva_vagas'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c18_programa_reserva_vagas'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c19_financiamento_estudantil'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c20_financiamento_estudantil'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c21_financiamento_estudantil'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c22_financiamento_estudantil'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c23_financiamento_estudantil'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c24_financiamento_estudantil'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c25_financiamento_estudantil'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c26_financiamento_estudantil_n_reemb'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c27_financiamento_estudantil_n_reemb'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c28_financiamento_estudantil_n_reemb'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c29_financiamento_estudantil_n_reemb'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c30_financiamento_estudantil_n_reemb'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c31_financiamento_estudantil_n_reemb'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c32_financiamento_estudantil_n_reemb'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c33_apoio_social'                         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c34_tipo_apoio_social'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c35_tipo_apoio_social'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c36_tipo_apoio_social'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c37_tipo_apoio_social'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c38_tipo_apoio_social'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c39_tipo_apoio_social'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c40_atividade_complementar'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c41_atividade_complementar'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c42_bolsa'                                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c43_atividade_complementar'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c44_bolsa'                                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c45_atividade_complementar'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c46_bolsa'                                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c47_atividade_complementar'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c48_bolsa'                                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c49_semestre_conclusao'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c50_aluno_parfor'                         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aluno_c24_def_autismo'                          => new sfValidatorPass(array('required' => false)),
      'aluno_c25_def_asperger'                         => new sfValidatorPass(array('required' => false)),
      'aluno_c26_def_rett'                             => new sfValidatorPass(array('required' => false)),
      'aluno_c27_def_tdi'                              => new sfValidatorPass(array('required' => false)),
      'aluno_c28_def_superdotado'                      => new sfValidatorPass(array('required' => false)),
      'curso_c51_semestre_referencia'                  => new sfValidatorPass(array('required' => false)),
      'curso_c52_curso_origem_transferencia'           => new sfValidatorPass(array('required' => false)),
      'curso_c53_forma_ingresso_seriada'               => new sfValidatorPass(array('required' => false)),
      'curso_c54_forma_ingresso_exofficio'             => new sfValidatorPass(array('required' => false)),
      'curso_c55_forma_ingresso_judicial'              => new sfValidatorPass(array('required' => false)),
      'curso_c56_mobilidade_academica'                 => new sfValidatorPass(array('required' => false)),
      'curso_c57_mobilidade_tipo'                      => new sfValidatorPass(array('required' => false)),
      'curso_c58_mobilidade_ies_destino'               => new sfValidatorPass(array('required' => false)),
      'curso_c59_mobilidade_tipo_internacional'        => new sfValidatorPass(array('required' => false)),
      'curso_c60_mobilidade_pais_destino'              => new sfValidatorPass(array('required' => false)),
      'curso_c61_semestre_ingresso_curso'              => new sfValidatorPass(array('required' => false)),
      'curso_c62_forma_ingresso_selecao_simples'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c63_forma_ingresso_selecao_remanescentes' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'curso_c64_forma_ingresso_selecao_especiais'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'exportado'                                      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
    ));

    $this->widgetSchema->setNameFormat('censo2009_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Censo2009';
  }

  public function getFields()
  {
    return array(
      'aluno_c1'                                       => 'Number',
      'aluno_c2'                                       => 'Text',
      'aluno_c3'                                       => 'Text',
      'aluno_c4_nome'                                  => 'Text',
      'aluno_c5_cpf'                                   => 'Text',
      'aluno_c6_doc_estrangeiro'                       => 'Text',
      'aluno_c7_nascimento'                            => 'Text',
      'aluno_c8_sexo'                                  => 'Number',
      'aluno_c9_cor_raca'                              => 'Number',
      'aluno_c10_mae'                                  => 'Text',
      'aluno_c11_nacionalidade'                        => 'Number',
      'aluno_c12_uf_nascimento'                        => 'Text',
      'aluno_c13_cidade_nascimento'                    => 'Text',
      'aluno_c14_pais_origem'                          => 'Text',
      'aluno_c15_deficiencia'                          => 'Number',
      'aluno_c16_def_cegueria'                         => 'Text',
      'aluno_c17_def_baixa_visao'                      => 'Text',
      'aluno_c18_def_surdez'                           => 'Text',
      'aluno_c19_def_auditiva'                         => 'Text',
      'aluno_c20_def_fisica'                           => 'Text',
      'aluno_c21_def_surdocegueira'                    => 'Text',
      'aluno_c22_def_multipla'                         => 'Text',
      'aluno_c23_def_mental'                           => 'Text',
      'curso_c1_tipo_reg2'                             => 'Number',
      'curso_c2_id_inep_curso'                         => 'Text',
      'curso_c3_cod_polo_inep'                         => 'Text',
      'curso_c4_turno_aluno'                           => 'Text',
      'curso_c5_situacao_vinculo'                      => 'Number',
      'curso_c6_data_ingresso'                         => 'Text',
      'curso_c7_aluno_publica'                         => 'Text',
      'curso_c8_forma_ingresso_selecao_vestibular'     => 'Number',
      'curso_c9_forma_ingresso_selecao_enem'           => 'Number',
      'curso_c10_forma_ingresso_selecao_outros'        => 'Number',
      'curso_c11_forma_ingresso_selecao_pecg'          => 'Number',
      'curso_c12_forma_ingresso_outras'                => 'Number',
      'curso_c13_programa_reserva_vagas'               => 'Number',
      'curso_c14_programa_reserva_vagas'               => 'Number',
      'curso_c15_programa_reserva_vagas'               => 'Number',
      'curso_c16_programa_reserva_vagas'               => 'Number',
      'curso_c17_programa_reserva_vagas'               => 'Number',
      'curso_c18_programa_reserva_vagas'               => 'Number',
      'curso_c19_financiamento_estudantil'             => 'Number',
      'curso_c20_financiamento_estudantil'             => 'Number',
      'curso_c21_financiamento_estudantil'             => 'Number',
      'curso_c22_financiamento_estudantil'             => 'Number',
      'curso_c23_financiamento_estudantil'             => 'Number',
      'curso_c24_financiamento_estudantil'             => 'Number',
      'curso_c25_financiamento_estudantil'             => 'Number',
      'curso_c26_financiamento_estudantil_n_reemb'     => 'Number',
      'curso_c27_financiamento_estudantil_n_reemb'     => 'Number',
      'curso_c28_financiamento_estudantil_n_reemb'     => 'Number',
      'curso_c29_financiamento_estudantil_n_reemb'     => 'Number',
      'curso_c30_financiamento_estudantil_n_reemb'     => 'Number',
      'curso_c31_financiamento_estudantil_n_reemb'     => 'Number',
      'curso_c32_financiamento_estudantil_n_reemb'     => 'Number',
      'curso_c33_apoio_social'                         => 'Number',
      'curso_c34_tipo_apoio_social'                    => 'Number',
      'curso_c35_tipo_apoio_social'                    => 'Number',
      'curso_c36_tipo_apoio_social'                    => 'Number',
      'curso_c37_tipo_apoio_social'                    => 'Number',
      'curso_c38_tipo_apoio_social'                    => 'Number',
      'curso_c39_tipo_apoio_social'                    => 'Number',
      'curso_c40_atividade_complementar'               => 'Number',
      'curso_c41_atividade_complementar'               => 'Number',
      'curso_c42_bolsa'                                => 'Number',
      'curso_c43_atividade_complementar'               => 'Number',
      'curso_c44_bolsa'                                => 'Number',
      'curso_c45_atividade_complementar'               => 'Number',
      'curso_c46_bolsa'                                => 'Number',
      'curso_c47_atividade_complementar'               => 'Number',
      'curso_c48_bolsa'                                => 'Number',
      'curso_c49_semestre_conclusao'                   => 'Number',
      'curso_c50_aluno_parfor'                         => 'Number',
      'aluno_c24_def_autismo'                          => 'Text',
      'aluno_c25_def_asperger'                         => 'Text',
      'aluno_c26_def_rett'                             => 'Text',
      'aluno_c27_def_tdi'                              => 'Text',
      'aluno_c28_def_superdotado'                      => 'Text',
      'curso_c51_semestre_referencia'                  => 'Text',
      'curso_c52_curso_origem_transferencia'           => 'Text',
      'curso_c53_forma_ingresso_seriada'               => 'Text',
      'curso_c54_forma_ingresso_exofficio'             => 'Text',
      'curso_c55_forma_ingresso_judicial'              => 'Text',
      'curso_c56_mobilidade_academica'                 => 'Text',
      'curso_c57_mobilidade_tipo'                      => 'Text',
      'curso_c58_mobilidade_ies_destino'               => 'Text',
      'curso_c59_mobilidade_tipo_internacional'        => 'Text',
      'curso_c60_mobilidade_pais_destino'              => 'Text',
      'curso_c61_semestre_ingresso_curso'              => 'Text',
      'curso_c62_forma_ingresso_selecao_simples'       => 'Number',
      'curso_c63_forma_ingresso_selecao_remanescentes' => 'Number',
      'curso_c64_forma_ingresso_selecao_especiais'     => 'Number',
      'exportado'                                      => 'Boolean',
      'id'                                             => 'Number',
    );
  }
}
