# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure: true

index:
  credentials: [aplicacao]

new:
  credentials: [aplicacao]

create:
  credentials: [aplicacao]

edit:
  credentials: [aplicacao]

update:
  credentials: [aplicacao]

delete:
  credentials: [aplicacao]