generator:
  class: sfPropelGenerator
  param:
    model_class:           tbconceito
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tbconceito
    plural:                tbconceitos
    route_prefix:          tbconceito
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=descricao,sucinto,sigla_pingifes]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
