generator:
  class: sfPropelGenerator
  param:
    model_class:           tbaluno
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tbaluno
    plural:                tbalunos
    route_prefix:          tbaluno
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        actions:
          _new: ~
          AbandonoDeCurso: { label: Abandono de Curso }
        display: [=matricula,nome,cpf,Tbcursoversao,Tbalunosituacao,Tbtipoingresso,enade]
        object_actions:
          _delete: ~
          _edit: ~
#          LimpaTurmas: {label: Remover Turmas}
          GeraFicha: {label: Ficha de Aluno}
          GeraFila: {label: Fila}
          AlteraMatricula: {label: Alterar Matricula}
          Aproveitamento: {label: Aproveitamento }
          Pendencia: {label: Pendência }
          Enade: {label: ENADE, action: Enade }
        batch_actions:
          mudarPolo: {label: Mudar pólo dos alunos para...}
          mudarVersaoCurso: {label: Mudar Versão de curso para...}
          EnviarEmail: {label: Enviar Email para...}
          MudarSituacaoAluno: {label: Mudar situacao dos alunos para...}
          MatricularAlunos: {label: Matricular no semestre ...}
          AlteraDtIngresso: { label: Alterar data de ingresso... }
        #  RemoverDaFila: {label: Remover filas do semestre ...}
      filter:
        display: [matricula,nome,cpf,id_tipo_ingresso,dt_ingresso,id_situacao,dt_situacao,cod_curso,id_versao_curso,id_polo,sexo,id_raca,pingifes_sit_matricula,enade]
      form:
        display:
          "NONE": [matricula]
          "Dados Pessoais": [nome,sexo,estado_civil,celular,fone_residencial,id_neces_especial,dt_nascimento,nacionalidade,naturalidade,pai,mae,email,id_raca]
          "Documentos": [cpf,rg,rg_org_exped,rg_dt_exped,titulo,titulo_zona,titulo_secao,reservista]
          "Endereço": [cep,numero,complemento]
          "Dados Acadêmicos": [id_versao_curso,id_tipo_ingresso,id_polo,dt_ingresso,id_situacao,id_destino,dt_situacao,id_2grau,ano_concl_2grau,id_3grau,ano_concl_3grau,enade]
          "Trabalho": [id_trabalho,cep_trabalho,fone_trabalho,ramal_trabalho]        
        fields:
          enade: {label: 'Fez o ENADE?'}
          id_raca: {label: 'Raca/Cor'}
          id_trabalho: {label: Instituição}
          cep_trabalho: {label: CEP}
          fone_trabalho: {label: Telefone}
          ramal_trabalho: {label: Ramal}
          id_polo: {label: Pólo}
          id_destino: {label: Instituição de Destino , help: 'Instituição de Destino da Transferência'}
      edit:    ~
      new:        
        fields:
          matricula: {help: "Valor formado por: ano e semestre de ingresso, código do curso e posição no vestibular" }
      