generator:
  class: sfPropelGenerator
  param:
    model_class:           tbprofessorsituacao
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tbprofessorsituacao
    plural:                tbprofessorsituacaos
    route_prefix:          tbprofessorsituacao
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=descricao]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
